/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Config;
import Clases.ControlGrabado;
import Clases.ConvertirMayusculas;
import Conexion.BDConexion;
import Conexion.Conexion;
import Conexion.Control;
import Conexion.ObtenerFecha;
import DAO.cuentas_ahorroDAO;
import DAO.monedaDAO;
import DAO.tipo_ahorroDAO;
import Modelo.Tablas;
import Modelo.cuentas_ahorro;
import Modelo.moneda;
import Modelo.tipo_ahorro;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.openide.util.Exceptions;

/**
 *
 * @author FedeXavier
 */
public class cuentas_ahorros extends javax.swing.JFrame {

    Conexion con = null;
    Statement stm = null;
    Tablas modelo = new Tablas();
    Tablas modelotipoahorro = new Tablas();
    Tablas modelomoneda = new Tablas();

    JScrollPane scroll = new JScrollPane();
    private TableRowSorter trsfiltro, trsfiltropais,trsfiltrorubro;
    ImageIcon iconograbar = new ImageIcon("src/Iconos/grabar.png");
    ImageIcon iconobuscar = new ImageIcon("src/Iconos/buscar.png");
    ImageIcon icononuevo = new ImageIcon("src/Iconos/nuevo.png");
    ImageIcon iconoeditar = new ImageIcon("src/Iconos/editar.png");
    ImageIcon iconoborrar = new ImageIcon("src/Iconos/eliminar.png");
    ImageIcon iconoprint = new ImageIcon("src/Iconos/impresora.png");
    ImageIcon iconosalir = new ImageIcon("src/Iconos/salir.png");
    ObtenerFecha ODate = new ObtenerFecha();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat formato = new DecimalFormat("#,###.##");
    DecimalFormat formatosinpunto = new DecimalFormat("###");

    /**
     * Creates new form Template
     */
    public cuentas_ahorros() {
        initComponents();
        this.BotonAgregar.setIcon(icononuevo);
        this.BotonEditar.setIcon(iconoeditar);
        this.BuscarTipoCuenta.setIcon(iconobuscar);
        this.BuscarMoneda.setIcon(iconobuscar);
        this.BotonDelete.setIcon(iconoborrar);
        this.BotonPrint.setIcon(iconoprint);
        this.BotonClose.setIcon(iconosalir);
        this.BotonGrabar.setIcon(iconograbar);
        this.BotonSalir.setIcon(iconosalir);
        this.tablacuentas.setShowGrid(false);
        this.tablacuentas.setOpaque(true);
        this.tablacuentas.setBackground(new Color(102, 204, 255));
        this.tablacuentas.setForeground(Color.BLACK);

        this.setLocationRelativeTo(null); //Centramos el formulario
        this.jTextOpciones1.setVisible(false);
        this.Inicializar();
        this.cargarTitulo();
        this.TitPaises();
        this.TitRubros();

        GrillaCuentas GrillaOC = new GrillaCuentas();
        Thread HiloGrilla = new Thread(GrillaOC);
        HiloGrilla.start();

        GrillaTipoAhorro grillapa = new GrillaTipoAhorro();
        Thread hilodo = new Thread(grillapa);
        hilodo.start();

        GrillaMonedas grillaru = new GrillaMonedas();
        Thread hiloru = new Thread(grillaru);
        hiloru.start();

        
    }

    Control hand = new Control();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalle_cuenta = new javax.swing.JDialog();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        nombresocio = new javax.swing.JTextField();
        socio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipocuenta = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneda = new javax.swing.JTextField();
        BuscarMoneda = new javax.swing.JButton();
        nombremoneda = new javax.swing.JTextField();
        enviocorreo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        tipoahorro = new javax.swing.JTextField();
        BuscarTipoCuenta = new javax.swing.JButton();
        nombretipoahorro = new javax.swing.JTextField();
        fechaapertura = new com.toedter.calendar.JDateChooser();
        firmas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        caucion = new javax.swing.JCheckBox();
        sobregiro = new javax.swing.JCheckBox();
        estado = new javax.swing.JCheckBox();
        BuscarSocio = new javax.swing.JButton();
        panel3 = new org.edisoncor.gui.panel.Panel();
        BotonGrabar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BTipoAhorro = new javax.swing.JDialog();
        jPanel19 = new javax.swing.JPanel();
        combopais = new javax.swing.JComboBox<>();
        jTBuscarPais = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablatipoahorro = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        AceptarPais = new javax.swing.JButton();
        SalirPais = new javax.swing.JButton();
        BMonedas = new javax.swing.JDialog();
        jPanel21 = new javax.swing.JPanel();
        comborubro = new javax.swing.JComboBox<>();
        jTBuscarRubro = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablamoneda = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        AceptarRubro = new javax.swing.JButton();
        SalirRubro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonEditar = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonDelete = new javax.swing.JButton();
        BotonPrint = new javax.swing.JButton();
        BotonClose = new javax.swing.JButton();
        jTextOpciones1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacuentas = new javax.swing.JTable();
        panel2 = new org.edisoncor.gui.panel.Panel();
        etiquetasucursal = new org.edisoncor.gui.label.LabelMetric();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        detalle_cuenta.setTitle("Actualizar Sociedad Emisora");
        detalle_cuenta.setName("detalle_cuenta"); // NOI18N
        detalle_cuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                detalle_cuentaFocusGained(evt);
            }
        });
        detalle_cuenta.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                detalle_cuentaWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setForeground(new java.awt.Color(255, 0, 0));
        panel1.setToolTipText("");
        panel1.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel1.setName("panel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar Cuenta");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        codigo.setEditable(false);
        codigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigo.setEnabled(false);
        codigo.setName("codigo"); // NOI18N

        nombresocio.setName("nombresocio"); // NOI18N
        nombresocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresocioFocusLost(evt);
            }
        });
        nombresocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresocioKeyPressed(evt);
            }
        });

        socio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        socio.setName("socio"); // NOI18N
        socio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                socioKeyPressed(evt);
            }
        });

        jLabel7.setText("Cuenta");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel9.setText("Titular de la Cuenta");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Fecha Apertura");
        jLabel10.setName("jLabel10"); // NOI18N

        tipocuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Conjunta", "Indistinta" }));
        tipocuenta.setName("tipocuenta"); // NOI18N
        tipocuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocuentaActionPerformed(evt);
            }
        });
        tipocuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipocuentaKeyPressed(evt);
            }
        });

        jLabel13.setText("Modalidad de Firma");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel3.setText("Moneda");
        jLabel3.setName("jLabel3"); // NOI18N

        moneda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        moneda.setName("moneda"); // NOI18N
        moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaActionPerformed(evt);
            }
        });
        moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monedaKeyPressed(evt);
            }
        });

        BuscarMoneda.setName("BuscarMoneda"); // NOI18N
        BuscarMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMonedaActionPerformed(evt);
            }
        });

        nombremoneda.setEditable(false);
        nombremoneda.setName("nombremoneda"); // NOI18N

        enviocorreo.setText("Enviar Correo");
        enviocorreo.setName("enviocorreo"); // NOI18N

        jLabel6.setText("Tipo de Cuenta");
        jLabel6.setName("jLabel6"); // NOI18N

        tipoahorro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tipoahorro.setName("tipoahorro"); // NOI18N
        tipoahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoahorroActionPerformed(evt);
            }
        });
        tipoahorro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipoahorroKeyPressed(evt);
            }
        });

        BuscarTipoCuenta.setName("BuscarTipoCuenta"); // NOI18N
        BuscarTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTipoCuentaActionPerformed(evt);
            }
        });

        nombretipoahorro.setEditable(false);
        nombretipoahorro.setName("nombretipoahorro"); // NOI18N

        fechaapertura.setName("fechaapertura"); // NOI18N
        fechaapertura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaaperturaFocusGained(evt);
            }
        });
        fechaapertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaaperturaKeyPressed(evt);
            }
        });

        firmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Una", "Dos" }));
        firmas.setName("firmas"); // NOI18N

        jLabel2.setText("Firmas");
        jLabel2.setName("jLabel2"); // NOI18N

        caucion.setText("Caución");
        caucion.setName("caucion"); // NOI18N

        sobregiro.setText("Sobregiro");
        sobregiro.setName("sobregiro"); // NOI18N

        estado.setText("Estado de la Cuenta");
        estado.setName("estado"); // NOI18N

        BuscarSocio.setName("BuscarSocio"); // NOI18N
        BuscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel2))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enviocorreo)
                                .addComponent(firmas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caucion)
                                .addComponent(sobregiro)
                                .addComponent(estado)
                                .addComponent(tipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(114, 114, 114)
                            .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(BuscarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nombremoneda))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(152, 152, 152)
                                    .addComponent(tipoahorro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6))
                            .addGap(39, 39, 39)
                            .addComponent(BuscarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nombretipoahorro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(117, 117, 117)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(fechaapertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(socio, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(BuscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nombresocio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombresocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(socio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BuscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fechaapertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BuscarTipoCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombretipoahorro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tipoahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombremoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(enviocorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sobregiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estado)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        panel3.setForeground(new java.awt.Color(255, 0, 0));
        panel3.setToolTipText("");
        panel3.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel3.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel3.setName("panel3"); // NOI18N

        BotonGrabar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonGrabar.setText("Grabar");
        BotonGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGrabar.setName("BotonGrabar"); // NOI18N
        BotonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGrabarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.setName("BotonSalir"); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(BotonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGrabar)
                    .addComponent(BotonSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout detalle_cuentaLayout = new javax.swing.GroupLayout(detalle_cuenta.getContentPane());
        detalle_cuenta.getContentPane().setLayout(detalle_cuentaLayout);
        detalle_cuentaLayout.setHorizontalGroup(
            detalle_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalle_cuentaLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detalle_cuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalle_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detalle_cuentaLayout.setVerticalGroup(
            detalle_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalle_cuentaLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BTipoAhorro.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        BTipoAhorro.setTitle("null");
        BTipoAhorro.setName("BTipoAhorro"); // NOI18N

        jPanel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setName("jPanel19"); // NOI18N

        combopais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        combopais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por Nombre", "Buscar por Código" }));
        combopais.setName("combopais"); // NOI18N

        jTBuscarPais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTBuscarPais.setName("jTBuscarPais"); // NOI18N
        jTBuscarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarPaisKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        tablatipoahorro.setModel(modelotipoahorro);
        tablatipoahorro.setName("tablatipoahorro"); // NOI18N
        tablatipoahorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablatipoahorroMouseClicked(evt);
            }
        });
        tablatipoahorro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablatipoahorroKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(tablatipoahorro);

        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setName("jPanel20"); // NOI18N

        AceptarPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AceptarPais.setText("Aceptar");
        AceptarPais.setName("AceptarPais"); // NOI18N
        AceptarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarPaisActionPerformed(evt);
            }
        });

        SalirPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SalirPais.setText("Salir");
        SalirPais.setName("SalirPais"); // NOI18N
        SalirPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(AceptarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarPais)
                    .addComponent(SalirPais))
                .addContainerGap())
        );

        javax.swing.GroupLayout BTipoAhorroLayout = new javax.swing.GroupLayout(BTipoAhorro.getContentPane());
        BTipoAhorro.getContentPane().setLayout(BTipoAhorroLayout);
        BTipoAhorroLayout.setHorizontalGroup(
            BTipoAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BTipoAhorroLayout.setVerticalGroup(
            BTipoAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTipoAhorroLayout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BMonedas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        BMonedas.setTitle("null");
        BMonedas.setName("BMonedas"); // NOI18N

        jPanel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setName("jPanel21"); // NOI18N

        comborubro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comborubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por Nombre", "Buscar por Código" }));
        comborubro.setName("comborubro"); // NOI18N

        jTBuscarRubro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTBuscarRubro.setName("jTBuscarRubro"); // NOI18N
        jTBuscarRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarRubroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comborubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTBuscarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comborubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBuscarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        tablamoneda.setModel(modelomoneda        );
        tablamoneda.setName("tablamoneda"); // NOI18N
        tablamoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablamonedaMouseClicked(evt);
            }
        });
        tablamoneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablamonedaKeyPressed(evt);
            }
        });
        jScrollPane8.setViewportView(tablamoneda);

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setName("jPanel22"); // NOI18N

        AceptarRubro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AceptarRubro.setText("Aceptar");
        AceptarRubro.setName("AceptarRubro"); // NOI18N
        AceptarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarRubroActionPerformed(evt);
            }
        });

        SalirRubro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SalirRubro.setText("Salir");
        SalirRubro.setName("SalirRubro"); // NOI18N
        SalirRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirRubroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(AceptarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalirRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarRubro)
                    .addComponent(SalirRubro))
                .addContainerGap())
        );

        javax.swing.GroupLayout BMonedasLayout = new javax.swing.GroupLayout(BMonedas.getContentPane());
        BMonedas.getContentPane().setLayout(BMonedasLayout);
        BMonedasLayout.setHorizontalGroup(
            BMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BMonedasLayout.setVerticalGroup(
            BMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BMonedasLayout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos de Sociedades Emisoras");
        setName("Form"); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setName("jPanel2"); // NOI18N

        BotonEditar.setBackground(new java.awt.Color(255, 255, 255));
        BotonEditar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonEditar.setText("Editar Registro");
        BotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEditar.setName("BotonEditar"); // NOI18N
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonAgregar.setText(" Agregar Registro");
        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.setName("BotonAgregar"); // NOI18N
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonDelete.setBackground(new java.awt.Color(255, 255, 255));
        BotonDelete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonDelete.setText("Eliminar Registro");
        BotonDelete.setToolTipText("");
        BotonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDelete.setName("BotonDelete"); // NOI18N
        BotonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeleteActionPerformed(evt);
            }
        });

        BotonPrint.setBackground(new java.awt.Color(255, 255, 255));
        BotonPrint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonPrint.setText("Listar/Imprimir");
        BotonPrint.setToolTipText("");
        BotonPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPrint.setName("BotonPrint"); // NOI18N
        BotonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrintActionPerformed(evt);
            }
        });

        BotonClose.setBackground(new java.awt.Color(255, 255, 255));
        BotonClose.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonClose.setText("     Salir");
        BotonClose.setToolTipText("");
        BotonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonClose.setName("BotonClose"); // NOI18N
        BotonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCloseActionPerformed(evt);
            }
        });

        jTextOpciones1.setEditable(false);
        jTextOpciones1.setName("jTextOpciones1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonPrint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BotonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(82, Short.MAX_VALUE)
                    .addComponent(jTextOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BotonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(331, Short.MAX_VALUE)
                    .addComponent(jTextOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(245, 245, 245)))
        );

        tablacuentas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusGained(evt);
            }
        });

        tablacuentas.setModel(modelo);
        tablacuentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablacuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablacuentas.setName("tablacuentas"); // NOI18N
        tablacuentas.setSelectionBackground(new java.awt.Color(51, 204, 255));
        tablacuentas.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tablacuentas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablacuentasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablacuentasFocusLost(evt);
            }
        });
        tablacuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacuentasMouseClicked(evt);
            }
        });
        tablacuentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablacuentasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablacuentas);

        panel2.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel2.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel2.setName("panel2"); // NOI18N

        etiquetasucursal.setText("Cuentas de Ahorro");
        etiquetasucursal.setName("etiquetasucursal"); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Código" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(0, 63, 62));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiquetasucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetasucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        this.jTextField1.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextField1.getText()).toUpperCase();
                jTextField1.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (jComboBox1.getSelectedIndex()) {
                    case 0:
                        indiceColumnaTabla = 1;
                        break;//por nombre
                    case 1:
                        indiceColumnaTabla = 0;
                        break;//por codigo
                }
                repaint();
                filtro(indiceColumnaTabla);
            }
        });
        trsfiltro = new TableRowSorter(tablacuentas.getModel());
        tablacuentas.setRowSorter(trsfiltro);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    public void filtropais(int nNumeroColumna) {
        trsfiltropais.setRowFilter(RowFilter.regexFilter(this.jTBuscarPais.getText(), nNumeroColumna));
    }

    private void TitPaises() {
        modelotipoahorro.addColumn("Código");
        modelotipoahorro.addColumn("Nombre");

        int[] anchos = {90, 200};
        for (int i = 0; i < modelotipoahorro.getColumnCount(); i++) {
            tablatipoahorro.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablatipoahorro.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablatipoahorro.getTableHeader().setFont(new Font("Arial Black", 1, 10));

        // Hacemos Invisible la Celda de Costos de los Productos
        Font font = new Font("Arial", Font.BOLD, 9);
        this.tablatipoahorro.setFont(font);

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        this.tablatipoahorro.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
    }

    
        public void filtrorubro(int nNumeroColumna) {
        trsfiltrorubro.setRowFilter(RowFilter.regexFilter(this.jTBuscarRubro.getText(), nNumeroColumna));
    }

    private void TitRubros() {
        modelomoneda.addColumn("Código");
        modelomoneda.addColumn("Nombre");

        int[] anchos = {90, 200};
        for (int i = 0; i < modelomoneda.getColumnCount(); i++) {
            tablamoneda.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablamoneda.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablamoneda.getTableHeader().setFont(new Font("Arial Black", 1, 10));

        // Hacemos Invisible la Celda de Costos de los Productos
        Font font = new Font("Arial", Font.BOLD, 9);
        this.tablamoneda.setFont(font);

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        this.tablamoneda.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
    }

    private void BotonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCloseActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCloseActionPerformed

    private void Inicializar() {
        Calendar c2 = new GregorianCalendar();
    }

    private void limpiar() {
        Calendar c2 = new GregorianCalendar();
        this.codigo.setText("0");
        this.nombresocio.setText("");
        this.socio.setText("");
/*      this.direccion.setText("");
        this.responsable.setText("");
        this.telefono.setText("");
        this.fax.setText("");*/
        this.tipoahorro.setText("0");
        this.nombretipoahorro.setText("");
        this.moneda.setText("0");
        this.nombremoneda.setText("");
        this.tipocuenta.setSelectedIndex(0);
//        this.tipoentidad.setSelectedIndex(0);
  //      this.clase.setSelectedIndex(0);
//      this.email.setText("");
        this.enviocorreo.setSelected(true);
    }


    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        codigo.setEnabled(true);
        this.limpiar();
        detalle_cuenta.setModal(true);
        detalle_cuenta.setSize(670, 565);
        //Establecemos un título para el jDialog
        detalle_cuenta.setTitle("Agregar nuevo Emisor");
        detalle_cuenta.setLocationRelativeTo(null);
        detalle_cuenta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void tablacuentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablacuentasKeyPressed
        int nFila = this.tablacuentas.getSelectedRow();
        this.jTextOpciones1.setText(this.tablacuentas.getValueAt(nFila, 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tablacuentasKeyPressed

    private void tablacuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacuentasMouseClicked
        int nFila = this.tablacuentas.getSelectedRow();
        this.jTextOpciones1.setText(this.tablacuentas.getValueAt(nFila, 0).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tablacuentasMouseClicked

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        this.limpiar();
        if (Integer.valueOf(Config.cNivelUsuario) == 1) {
            int nFila = this.tablacuentas.getSelectedRow();
            if (nFila < 0) {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar un Registro");
                this.tablacuentas.requestFocus();
                return;
            }

            this.codigo.setText(this.tablacuentas.getValueAt(nFila, 0).toString());
            cuentas_ahorroDAO emDAO = new cuentas_ahorroDAO();
            cuentas_ahorro em = null;
            try {
                em = emDAO.buscarId(Integer.valueOf(this.codigo.getText()));
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
            }
            if (em != null) {
           /*     nombre.setText(em.getNombre());
                socio.setText(em.getCedula());
                pais.setText(String.valueOf(em.getPais().getCodigo()));
                nombrenacionalidad.setText(em.getPais().getNombre().trim());
                telefono.setText(em.getTelefono());
                fax.setText(em.getFax());
                responsable.setText(em.getResponsable());
                email.setText(em.getEmail());
                direccion.setText(em.getDireccion());
                rubro.setText(String.valueOf(em.getRubro().getCodigo()));
                nombrerubro.setText(em.getRubro().getNombre());
                tiposociedad.setSelectedIndex(em.getTiposociedad()-1);
                tipoentidad.setSelectedIndex(em.getTipoentidad()-1);
                situacion.setSelectedItem(em.getSituacion());
                clase.setSelectedIndex(em.getClase()-1);
                if (em.getEstado() == 0) {
                    this.estado.setSelected(false);
                } else {
                    this.estado.setSelected(true);
                }
                */
                detalle_cuenta.setModal(true);
                detalle_cuenta.setSize(670, 565);
                //Establecemos un título para el jDialog
                detalle_cuenta.setTitle("Modificar Datos del Emisor");
                detalle_cuenta.setLocationRelativeTo(null);
                detalle_cuenta.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO NO AUTORIZADO");
            }
        }

        //Envio como parametro el Codigo para saber si voy a modificar
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void tablacuentasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablacuentasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tablacuentasFocusGained

    private void jScrollPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void BotonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeleteActionPerformed
        if (Integer.valueOf(Config.cNivelUsuario) == 1) {
            int nFila = tablacuentas.getSelectedRow();
            String num = tablacuentas.getValueAt(nFila, 0).toString();
            Object[] opciones = {"   Si   ", "   No   "};
            int ret = JOptionPane.showOptionDialog(null, "Desea Eliminar el Registro ? ", "Confirmación", 0, 3, null, opciones, opciones[0]);
            if (ret == 0) {
                cuentas_ahorroDAO emDAO = new cuentas_ahorroDAO();
                try {
                    cuentas_ahorro em = emDAO.buscarId((Integer.valueOf(num)));
                    if (em == null) {
                        JOptionPane.showMessageDialog(null, "Registro no Existe");
                    } else {
                       //emDAO.eliminarEmisor(Integer.valueOf(num));
                        JOptionPane.showMessageDialog(null, "Registro Eliminado Exitosamente");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no Autorizado");
            }
            GrillaCuentas GrillaOC = new GrillaCuentas();
            Thread HiloGrilla = new Thread(GrillaOC);
            HiloGrilla.start();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDeleteActionPerformed

    private void tablacuentasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablacuentasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tablacuentasFocusLost

    private void BotonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrintActionPerformed
        con = new Conexion();
        stm = con.conectar();
        try {
            Map parameters = new HashMap();
            parameters.put("", new String(""));
            JasperReport jr = null;
            URL url = getClass().getClassLoader().getResource("Reports/sucursales.jasper");
            jr = (JasperReport) JRLoader.loadObject(url);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(jr, null, stm.getConnection());
            JasperViewer ventana = new JasperViewer(masterPrint, false);
            ventana.setTitle("Vista Previa");
            ventana.setVisible(true);
        } catch (Exception e) {
            JDialog.setDefaultLookAndFeelDecorated(true);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_BotonPrintActionPerformed

    private void detalle_cuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detalle_cuentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_detalle_cuentaFocusGained

    private void detalle_cuentaWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_detalle_cuentaWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_detalle_cuentaWindowGainedFocus

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.detalle_cuenta.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGrabarActionPerformed
        Object[] opciones = {"   Si   ", "   No   "};
        int ret = JOptionPane.showOptionDialog(null, "Desea Guardar los Datos? ", "Confirmación", 0, 3, null, opciones, opciones[0]);
        if (ret == 0) {

            cuentas_ahorroDAO grabar = new cuentas_ahorroDAO();
            cuentas_ahorro em = new cuentas_ahorro();
            monedaDAO pDAO = new monedaDAO();
            moneda p = null;
            tipo_ahorroDAO emDAO = new tipo_ahorroDAO();
            tipo_ahorro r = null;
            try {
                p = pDAO.buscarId(Integer.valueOf(moneda.getText()));
                r = emDAO.buscarId(Integer.valueOf(tipoahorro.getText()));
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            }

            
            em.setEnviocorreo((this.enviocorreo.isSelected())?1:0);
            em.setEstado((this.estado.isSelected())?1:0);
            em.setCaucion((this.caucion.isSelected())?1:0);
            em.setSobregiro((this.sobregiro.isSelected())?1:0);

            
         /*   em.setSocio();
            em.setCedula(socio.getText());
            em.setDireccion(direccion.getText());
            em.setPais(p);
            em.setRubro(r);
            em.setResponsable(responsable.getText().trim());
            em.setTiposociedad(tiposociedad.getSelectedIndex()+1);
            em.setTipoentidad(tipoentidad.getSelectedIndex()+1);
            em.setClase(clase.getSelectedIndex()+1);
            em.setTelefono(telefono.getText());
            em.setFax(fax.getText());
            em.setEmail(this.email.getText());
            em.setNomalias(this.nomalias.getText());
            em.setSituacion(this.situacion.getSelectedItem().toString());
            em.setEstado(nestado);*/
            //try {
                if (Integer.valueOf(codigo.getText()) == 0) {
//                  grabar.insertarEmisor(em);
                } else {
  //                em.setCodigo(Integer.valueOf(codigo.getText()));
    //              grabar.actualizarEmisor(em);
                }
       //   } catch (SQLException ex) {
         //     Exceptions.printStackTrace(ex);
           // }
            detalle_cuenta.setVisible(false);
            detalle_cuenta.setModal(false);

            GrillaCuentas GrillaOC = new GrillaCuentas();
            Thread HiloGrilla = new Thread(GrillaOC);
            HiloGrilla.start();
        }
    }//GEN-LAST:event_BotonGrabarActionPerformed

    private void nombresocioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresocioKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.socio.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
//            this.nomalias.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_nombresocioKeyPressed

    private void tipocuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocuentaActionPerformed
        System.out.println(this.tipocuenta.getSelectedItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocuentaActionPerformed

    private void nombresocioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresocioFocusLost
        String letras = ConvertirMayusculas.cadena(nombresocio);
        nombresocio.setText(letras);
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresocioFocusLost

    private void tablatipoahorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablatipoahorroMouseClicked
        this.AceptarPais.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablatipoahorroMouseClicked

    private void tablatipoahorroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablatipoahorroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.AceptarPais.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablatipoahorroKeyPressed

    private void jTBuscarPaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarPaisKeyPressed
        this.jTBuscarPais.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTBuscarPais.getText()).toUpperCase();
                jTBuscarPais.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (combopais.getSelectedIndex()) {
                    case 0:
                        indiceColumnaTabla = 1;
                        break;//por nombre
                    case 1:
                        indiceColumnaTabla = 0;
                }
                repaint();
                filtropais(indiceColumnaTabla);
            }
        });
        trsfiltropais = new TableRowSorter(tablatipoahorro.getModel());
        tablatipoahorro.setRowSorter(trsfiltropais);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarPaisKeyPressed

    private void AceptarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarPaisActionPerformed
        int nFila = this.tablatipoahorro.getSelectedRow();
        this.moneda.setText(this.tablatipoahorro.getValueAt(nFila, 0).toString());
        this.nombremoneda.setText(this.tablatipoahorro.getValueAt(nFila, 1).toString());
        this.BTipoAhorro.setVisible(false);
        this.jTBuscarPais.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarPaisActionPerformed

    private void SalirPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirPaisActionPerformed
        this.BTipoAhorro.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirPaisActionPerformed

    private void BuscarMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMonedaActionPerformed
        monedaDAO baDAO = new monedaDAO();
        moneda ba = null;
        try {
            ba = baDAO.buscarId(Integer.valueOf(this.moneda.getText()));
            if (ba.getCodigo() == 0) {
                BTipoAhorro.setModal(true);
                BTipoAhorro.setSize(482, 575);
                BTipoAhorro.setLocationRelativeTo(null);
                BTipoAhorro.setVisible(true);
                BTipoAhorro.setTitle("Buscar Paises");
            } else {
                nombremoneda.setText(ba.getNombre());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
//      responsable.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarMonedaActionPerformed

    private void monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaActionPerformed
        this.BuscarMoneda.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaActionPerformed

    private void monedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monedaKeyPressed
/*         if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.responsable.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.clase.requestFocus();
        }*/
     // TODO add your handling code here:
    }//GEN-LAST:event_monedaKeyPressed

    private void tipocuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipocuentaKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
//          this.tipoentidad.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.tipoahorro.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocuentaKeyPressed

    private void tipoahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoahorroActionPerformed
        this.BuscarTipoCuenta.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoahorroActionPerformed

    private void tipoahorroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoahorroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
//          this.direccion.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoahorroKeyPressed

    private void BuscarTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTipoCuentaActionPerformed
        monedaDAO ruDAO = new monedaDAO();
        moneda ru = null;
        try {
            ru = ruDAO.buscarId(Integer.valueOf(this.tipoahorro.getText()));
            if (ru.getCodigo() == 0) {
                BMonedas.setModal(true);
                BMonedas.setSize(482, 575);
                BMonedas.setLocationRelativeTo(null);
                BMonedas.setVisible(true);
                BMonedas.setTitle("Buscar Rubro");
            } else {
                nombremoneda.setText(ru.getNombre());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        tipocuenta.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTipoCuentaActionPerformed

    private void jTBuscarRubroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarRubroKeyPressed
        this.jTBuscarRubro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTBuscarRubro.getText()).toUpperCase();
                jTBuscarRubro.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (comborubro.getSelectedIndex()) {
                    case 0:
                    indiceColumnaTabla = 1;
                    break;//por nombre
                    case 1:
                    indiceColumnaTabla = 0;
                }
                repaint();
                filtrorubro(indiceColumnaTabla);
            }
        });
        trsfiltropais = new TableRowSorter(tablatipoahorro.getModel());
        tablatipoahorro.setRowSorter(trsfiltropais);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarRubroKeyPressed

    private void tablamonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamonedaMouseClicked
        this.AceptarRubro.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamonedaMouseClicked

    private void tablamonedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamonedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.AceptarRubro.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamonedaKeyPressed

    private void AceptarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarRubroActionPerformed
        int nFila = this.tablamoneda.getSelectedRow();
        this.tipoahorro.setText(this.tablamoneda.getValueAt(nFila, 0).toString());
        this.nombretipoahorro.setText(this.tablamoneda.getValueAt(nFila, 1).toString());
        this.BMonedas.setVisible(false);
        this.jTBuscarRubro.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarRubroActionPerformed

    private void SalirRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirRubroActionPerformed
        this.BMonedas.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirRubroActionPerformed

    private void socioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socioKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
//          this.direccion.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.nombresocio.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_socioKeyPressed

    private void fechaaperturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaaperturaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaaperturaFocusGained

    private void fechaaperturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaaperturaKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) {
//          this.comprobante.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
  //        this.factura.requestFocus();
        }
        // TODO add your handling code here:*/
    }//GEN-LAST:event_fechaaperturaKeyPressed

    private void BuscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarSocioActionPerformed

    public void filtro(int nNumeroColumna) {
        trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), nNumeroColumna));
    }

    private void cargarTitulo() {
        modelo.addColumn("Cuenta");
        modelo.addColumn("Títular");
        modelo.addColumn("Tipo de Cuenta");
        modelo.addColumn("Apertura");
        int[] anchos = {90, 200, 150,100};
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            tablacuentas.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablacuentas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablacuentas.getTableHeader().setFont(new Font("Arial Black", 1, 11));

        Font font = new Font("Arial", Font.BOLD, 10);
        this.tablacuentas.setFont(font);

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer AlinearCentro = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        AlinearCentro.setHorizontalAlignment(SwingConstants.CENTER);
        this.tablacuentas.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
        this.tablacuentas.getColumnModel().getColumn(3).setCellRenderer(AlinearCentro);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {    //</editor-fold>
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuentas_ahorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarPais;
    private javax.swing.JButton AceptarRubro;
    private javax.swing.JDialog BMonedas;
    private javax.swing.JDialog BTipoAhorro;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonClose;
    private javax.swing.JButton BotonDelete;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonGrabar;
    private javax.swing.JButton BotonPrint;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BuscarMoneda;
    private javax.swing.JButton BuscarSocio;
    private javax.swing.JButton BuscarTipoCuenta;
    private javax.swing.JButton SalirPais;
    private javax.swing.JButton SalirRubro;
    private javax.swing.JCheckBox caucion;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> combopais;
    private javax.swing.JComboBox<String> comborubro;
    private javax.swing.JDialog detalle_cuenta;
    private javax.swing.JCheckBox enviocorreo;
    private javax.swing.JCheckBox estado;
    private org.edisoncor.gui.label.LabelMetric etiquetasucursal;
    private com.toedter.calendar.JDateChooser fechaapertura;
    private javax.swing.JComboBox<String> firmas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTBuscarPais;
    private javax.swing.JTextField jTBuscarRubro;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextOpciones1;
    private javax.swing.JTextField moneda;
    private javax.swing.JTextField nombremoneda;
    private javax.swing.JTextField nombresocio;
    private javax.swing.JTextField nombretipoahorro;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JCheckBox sobregiro;
    private javax.swing.JTextField socio;
    private javax.swing.JTable tablacuentas;
    private javax.swing.JTable tablamoneda;
    private javax.swing.JTable tablatipoahorro;
    private javax.swing.JTextField tipoahorro;
    private javax.swing.JComboBox<String> tipocuenta;
    // End of variables declaration//GEN-END:variables

    private class GrillaCuentas extends Thread {

        public void run() {

            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
            int cantidadRegistro = modelo.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelo.removeRow(0);
            }

            cuentas_ahorroDAO DAO = new cuentas_ahorroDAO();
            try {
                for (cuentas_ahorro em : DAO.todos()) {
                    String Datos[] = {String.valueOf(em.getCuenta()),
                        em.getSocio().getNombre(), 
                        em.getTipoahorro().getNombre(),
                        formatoFecha.format(em.getFechaapertura())};
                    modelo.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablacuentas.setRowSorter(new TableRowSorter(modelo));
            int cantFilas = tablacuentas.getRowCount();
            if (cantFilas > 0) {
                BotonEditar.setEnabled(true);
                BotonDelete.setEnabled(true);
                BotonPrint.setEnabled(true);
            } else {
                BotonEditar.setEnabled(false);
                BotonDelete.setEnabled(false);
                BotonPrint.setEnabled(false);
            }
        }
    }

    private class GrillaTipoAhorro extends Thread {

        public void run() {

            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
            int cantidadRegistro = modelotipoahorro.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelotipoahorro.removeRow(0);
            }
            tipo_ahorroDAO bcDAO = new tipo_ahorroDAO();
            try {
                for (tipo_ahorro ba : bcDAO.todos()) {
                    String Datos[] = {String.valueOf(ba.getCodigo()), ba.getNombre()};
                    modelotipoahorro.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablatipoahorro.setRowSorter(new TableRowSorter(modelotipoahorro));
            int cantFilas = tablatipoahorro.getRowCount();
        }
    }


    private class GrillaMonedas extends Thread {

        public void run() {

            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
            int cantidadRegistro = modelomoneda.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelomoneda.removeRow(0);
            }
            monedaDAO ruDAO = new monedaDAO();
            try {
                for (moneda ru : ruDAO.todos()) {
                    String Datos[] = {String.valueOf(ru.getCodigo()), ru.getNombre()};
                    modelomoneda.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablamoneda.setRowSorter(new TableRowSorter(modelomoneda));
            int cantFilas = tablamoneda.getRowCount();
        }
    }

}
