/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.ConvertirMayusculas;
import Conexion.Conexion;
import Conexion.Control;
import Conexion.ObtenerFecha;
import Modelo.Tablas;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.openide.util.Exceptions;

/**
 *
 * @author FedeXavier
 */
public class cumplimiento_requisito extends javax.swing.JFrame {

    Conexion con = null;
    Statement stm = null;
    Tablas modelojuridico = new Tablas();
    Tablas modelofisica = new Tablas();

    JScrollPane scroll = new JScrollPane();
    private TableRowSorter trsfiltro, trsfiltrosucursal;
    ImageIcon icononuevo = new ImageIcon("src/Iconos/nuevo.png");
    ImageIcon iconograbar = new ImageIcon("src/Iconos/grabar.png");
    ImageIcon iconoeditar = new ImageIcon("src/Iconos/editar.png");
    ImageIcon iconoborrar = new ImageIcon("src/Iconos/eliminar.png");
    ImageIcon iconoprint = new ImageIcon("src/Iconos/impresora.png");
    ImageIcon iconosalir = new ImageIcon("src/Iconos/salir.png");
    ImageIcon iconobuscar = new ImageIcon("src/Iconos/buscar.png");
    ImageIcon icorefresh = new ImageIcon("src/Iconos/refrescar.png");
    ObtenerFecha ODate = new ObtenerFecha();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat formato = new DecimalFormat("#,###.##");
    DecimalFormat formatosinpunto = new DecimalFormat("###");

    /**
     * Creates new form Template
     */
    public cumplimiento_requisito() {
        initComponents();
        id1.setVisible(false);
        this.BotonSalir.setIcon(iconosalir);

        this.setLocationRelativeTo(null); //Centramos el formulario
//      this.cargarTitulo();
        this.TituloJuridico();
//      this.TituloMateria();
        GrillaJuridica GrillaOC = new GrillaJuridica();
        Thread HiloGrilla = new Thread(GrillaOC);
        HiloGrilla.start();

        GrillaFacultad GrillaSe = new GrillaFacultad();
        Thread HiloSe = new Thread(GrillaSe);
        HiloSe.start();
    }

    Control hand = new Control();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        descripcion0 = new javax.swing.JTextField();
        id0 = new javax.swing.JFormattedTextField();
        BotonAgregar0 = new javax.swing.JButton();
        BotonActualizar0 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablafisica = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablajuridica = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        id1 = new javax.swing.JFormattedTextField();
        descripcion1 = new javax.swing.JTextField();
        BotonAgregar1 = new javax.swing.JButton();
        BotonActualizar1 = new javax.swing.JButton();
        panel4 = new org.edisoncor.gui.panel.Panel();
        BotonSalir = new javax.swing.JButton();
        panel5 = new org.edisoncor.gui.panel.Panel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos de Carreras");
        setName("Form"); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        jPanel9.setName("jPanel9"); // NOI18N

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setName("jPanel10"); // NOI18N

        jLabel20.setText("Descripción");
        jLabel20.setName("jLabel20"); // NOI18N

        descripcion0.setName("descripcion0"); // NOI18N
        descripcion0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcion0FocusLost(evt);
            }
        });

        id0.setEditable(false);
        id0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        id0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        id0.setName("id0"); // NOI18N

        BotonAgregar0.setText("Agregar");
        BotonAgregar0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar0.setName("BotonAgregar0"); // NOI18N
        BotonAgregar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar0ActionPerformed(evt);
            }
        });

        BotonActualizar0.setText("Actualizar");
        BotonActualizar0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonActualizar0.setName("BotonActualizar0"); // NOI18N
        BotonActualizar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizar0ActionPerformed(evt);
            }
        });

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        tablafisica.setModel(modelofisica);
        tablafisica.setName("tablafisica"); // NOI18N
        tablafisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablafisicaKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tablafisica);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion0, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(93, 93, 93)
                                .addComponent(id0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonAgregar0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonActualizar0, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(id0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BotonAgregar0)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonActualizar0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Personas Fïsicas", jPanel9);

        jPanel11.setName("jPanel11"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        tablajuridica.setModel(modelojuridico);
        tablajuridica.setName("tablajuridica"); // NOI18N
        tablajuridica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablajuridicaKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tablajuridica);

        jLabel18.setText("Descripción");
        jLabel18.setName("jLabel18"); // NOI18N

        id1.setEditable(false);
        id1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        id1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        id1.setName("id1"); // NOI18N

        descripcion1.setName("descripcion1"); // NOI18N
        descripcion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcion1FocusLost(evt);
            }
        });

        BotonAgregar1.setText("Agregar");
        BotonAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar1.setName("BotonAgregar1"); // NOI18N
        BotonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar1ActionPerformed(evt);
            }
        });

        BotonActualizar1.setText("Actualizar");
        BotonActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonActualizar1.setName("BotonActualizar1"); // NOI18N
        BotonActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(93, 93, 93)
                                .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonActualizar1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BotonAgregar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonActualizar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Personas Juridicas", jPanel11);

        panel4.setBackground(new java.awt.Color(255, 255, 255));
        panel4.setForeground(new java.awt.Color(255, 0, 0));
        panel4.setToolTipText("");
        panel4.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel4.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel4.setName("panel4"); // NOI18N

        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.setName("BotonSalir"); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        panel5.setBackground(new java.awt.Color(255, 255, 255));
        panel5.setForeground(new java.awt.Color(255, 0, 0));
        panel5.setToolTipText("");
        panel5.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel5.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel5.setName("panel5"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Requisitos para Cumplimientos");
        jLabel19.setName("jLabel19"); // NOI18N

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void limpiar() {
        this.id1.setText("0");
        this.descripcion1.setText("");
    }


    private void TituloJuridico() {
        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        modelojuridico.addColumn("Id");
        modelojuridico.addColumn("Item");
        modelojuridico.addColumn("Descripción");
        int[] anchos = {0,100,250};
        for (int i = 0; i < modelojuridico.getColumnCount(); i++) {
            tablajuridica.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablajuridica.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablajuridica.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
        //Se usa para poner invisible una determinada celda
        tablajuridica.getTableHeader().setFont(new Font("Arial Black", 1, 10));
        Font font = new Font("Arial", Font.BOLD, 10);
        tablajuridica.setFont(font);

        this.tablajuridica.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablajuridica.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablajuridica.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablajuridica.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }


    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void tablajuridicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablajuridicaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablajuridicaKeyPressed

    private void descripcion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcion1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcion1FocusLost

    private void BotonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregar1ActionPerformed

    private void BotonActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizar1ActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void descripcion0FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcion0FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcion0FocusLost

    private void BotonAgregar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregar0ActionPerformed

    private void BotonActualizar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizar0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizar0ActionPerformed

    private void tablafisicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablafisicaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablafisicaKeyPressed

    private void TituloFisica() {
        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        modelofisica.addColumn("Id");
        modelofisica.addColumn("Item");
        modelofisica.addColumn("Descripción");
        int[] anchos = {0,100,250};
        for (int i = 0; i < modelofisica.getColumnCount(); i++) {
            tablafisica.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablafisica.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablafisica.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
        tablafisica.getColumnModel().getColumn(2).setCellRenderer(TablaRenderer);
        //Se usa para poner invisible una determinada celda
        tablafisica.getTableHeader().setFont(new Font("Arial Black", 1, 10));
        Font font = new Font("Arial", Font.BOLD, 10);
        tablafisica.setFont(font);

        this.tablafisica.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablafisica.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablafisica.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablafisica.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    private void LimpiarPFisica() {
        id0.setText("0");
        descripcion0.setText("");
    }

  /*private void CargarMateria(int nsemestre) {
        int ncarrera = Integer.valueOf(this.codigo.getText());
        int cantidadRegistro = modelomateria.getRowCount();
        for (int i = 1; i <= cantidadRegistro; i++) {
            modelomateria.removeRow(0);
        }
        materiasDAO detDAO = new materiasDAO();
        try {
            for (materias detvta : detDAO.todosxCarreraxSemestre(ncarrera, nsemestre)) {
                String Detalle[] = {String.valueOf(detvta.getIdmateria()), detvta.getNombre(), String.valueOf(detvta.getCargahoraria()), String.valueOf(detvta.getCodigo())};
                modelomateria.addRow(Detalle);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
        int cantFilas = tablamateria.getRowCount();
        if (cantFilas > 0) {
            BotonGrabarMateria.setEnabled(true);
            BotonBorrarMateria.setEnabled(true);
        } else {
            BotonGrabarMateria.setEnabled(true);
            BotonBorrarMateria.setEnabled(false);
        }

    }*/

    private void CargarSemestre() {
     /* int cantidadRegistro = modelosemestre.getRowCount();
        for (int i = 1; i <= cantidadRegistro; i++) {
            modelosemestre.removeRow(0);
        }
        semestresDAO detDAO = new semestresDAO();
        try {
            for (semestres detvta : detDAO.todosxCarrera(Integer.valueOf(this.codigo.getText()))) {
                String Detalle[] = {String.valueOf(detvta.getSemestre()), detvta.getNombre(), String.valueOf(detvta.getIditem())};
                modelosemestre.addRow(Detalle);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
        int cantFilas = tablasemestre.getRowCount();
        if (cantFilas > 0) {
            BotonAgregarSemestre.setEnabled(true);
            BotonBorrar.setEnabled(true);
        } else {
            BotonAgregarSemestre.setEnabled(true);
            BotonBorrar.setEnabled(false);
        }
        */
    }



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {    //</editor-fold>
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cumplimiento_requisito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar0;
    private javax.swing.JButton BotonActualizar1;
    private javax.swing.JButton BotonAgregar0;
    private javax.swing.JButton BotonAgregar1;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField descripcion0;
    private javax.swing.JTextField descripcion1;
    private javax.swing.JFormattedTextField id0;
    private javax.swing.JFormattedTextField id1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.Panel panel5;
    private javax.swing.JTable tablafisica;
    private javax.swing.JTable tablajuridica;
    // End of variables declaration//GEN-END:variables

    private class GrillaJuridica extends Thread {

      public void run() {

            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
           /* int cantidadRegistro = modelo.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelo.removeRow(0);
            }

            carreraDAO DAO = new carreraDAO();
            try {
                for (carrera suc : DAO.todos()) {
                    String Datos[] = {String.valueOf(suc.getCodigo()), suc.getNombre(), suc.getFacultad().getNombre(), suc.getTitulo(), String.valueOf(suc.getSemestres())};
                    modelo.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablacarrera.setRowSorter(new TableRowSorter(modelo));
            int cantFilas = tablacarrera.getRowCount();
            if (cantFilas > 0) {
                BotonEditar.setEnabled(true);
                BotonDelete.setEnabled(true);
                BotonPrint.setEnabled(true);
            } else {
                BotonEditar.setEnabled(false);
                BotonDelete.setEnabled(false);
                BotonPrint.setEnabled(false);
            }
            
            */
        }
    }

    private class GrillaFacultad extends Thread {

         public void run() {

          //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
          /*  int cantidadRegistro = modelosucursal.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelosucursal.removeRow(0);
            }

            facultadDAO DAOSUC = new facultadDAO();
            try {
                for (facultad suc : DAOSUC.todos()) {
                    String Datos[] = {String.valueOf(suc.getCodigo()), suc.getNombre()};
                    modelosucursal.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablasucursal.setRowSorter(new TableRowSorter(modelosucursal));
            int cantFilas = tablasucursal.getRowCount();
            */
        }
    }
    
}
         
