/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaUsuarios.java
 *
 * Created on 26-mar-2011, 15:51:22
 */
package Vista;

import Clases.Config;
import Clases.Parametros;
import Clases.TablaCobros;
import Conexion.Conexion;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableRowSorter;
import org.openide.util.Exceptions;

/**
 *
 * @author One
 */
public class cuotas_pendientes extends javax.swing.JFrame {

    String cValorActual, cDescuentos = null;
    double sumatoria, sumtotal, nDescuentos, nTotalPago, nTotalDeuda = 0.00;

    Conexion con = null;
    Statement stm = null;
    TablaCobros modelo = new TablaCobros();

    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat formato = new DecimalFormat("#,###.##");
    private TableRowSorter trsfiltro;

    /**
     * Creates new form ConsultaUsuarios
     */
    public cuotas_pendientes(String cCliente) {
        initComponents();
        //modelo. .setEsEditable(new boolean[] {true,true,false});
        this.descuentoxpagos.setHorizontalAlignment(JTextField.RIGHT);
        this.totaldeuda.setHorizontalAlignment(JTextField.RIGHT);
        this.capital.setHorizontalAlignment(JTextField.RIGHT);
        this.interesordinario.setHorizontalAlignment(JTextField.RIGHT);
        this.interesavencer.setHorizontalAlignment(JTextField.RIGHT);
        this.interesvencido.setHorizontalAlignment(JTextField.RIGHT);
        this.totalpago.setHorizontalAlignment(JTextField.RIGHT);
        this.totalpago.setText("0");
        this.setLocationRelativeTo(null); //Centramos el formulario
        this.codcliente.setText(cCliente);
        this.codcliente.setVisible(false);
        cargarTitulo();
        String cSql = "SELECT cuenta_clientes.*,clientes.categoria,clientes.asesor,clientes.nombre as nombrecliente,DATEDIFF(curdate(),cuenta_clientes.vencimiento) AS atraso,";
        cSql = cSql + "clientes.celular, clientes.direccion, clientes.mail,comprobantes.nomalias,DATEDIFF(CURDATE(),fecha_pago) AS di,";
        cSql = cSql + "comprobantes.diasgracia_gastos,comprobantes.diasgracia,comprobantes.interesmora,comprobantes.gastoscobros ";
        cSql = cSql + "FROM cuenta_clientes ";
        cSql = cSql + "INNER JOIN CLIENTES ";
        cSql = cSql + "ON clientes.codigo=cuenta_clientes.cliente ";
        cSql = cSql + "INNER JOIN comprobantes ";
        cSql = cSql + "ON comprobantes.codigo=cuenta_clientes.comprobante ";
        cSql = cSql + "WHERE cuenta_clientes.saldo>0 ";
        cSql = cSql + "and cuenta_clientes.moneda=1 ";
        cSql = cSql + "and cuenta_clientes.cliente= " + cCliente;
        cSql = cSql + " and cuenta_clientes.comprobante in (8,9,10) ";
        cSql = cSql + "ORDER by cuenta_clientes.vencimiento";

        cargarTabla(cSql);
        Buscar.setText("");
        Buscar.requestFocus();
        ResumenCuenta Resumen = new ResumenCuenta();
        Thread HiloResumen = new Thread(Resumen);
        HiloResumen.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonElegir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        panelTranslucidoComplete21 = new org.edisoncor.gui.panel.PanelTranslucidoComplete2();
        Buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        codcliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totaldeuda = new javax.swing.JFormattedTextField();
        capital = new javax.swing.JFormattedTextField();
        interesordinario = new javax.swing.JFormattedTextField();
        interesvencido = new javax.swing.JFormattedTextField();
        interesavencer = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxcuotas = new javax.swing.JCheckBox();
        boxdescuentos = new javax.swing.JCheckBox();
        totalpago = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        descuentoxpagos = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Cuotas");
        setAlwaysOnTop(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(modelo);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonElegir.setText("Seleccionar");
        jButtonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElegirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Salir");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        panelTranslucidoComplete21.setColorPrimario(new java.awt.Color(102, 153, 255));
        panelTranslucidoComplete21.setColorSecundario(new java.awt.Color(0, 204, 255));

        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Filtrar Busqueda por");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "RUC", "Código" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucidoComplete21Layout = new javax.swing.GroupLayout(panelTranslucidoComplete21);
        panelTranslucidoComplete21.setLayout(panelTranslucidoComplete21Layout);
        panelTranslucidoComplete21Layout.setHorizontalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucidoComplete21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(codcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTranslucidoComplete21Layout.setVerticalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucidoComplete21Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                        .addGroup(panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        jLabel3.setText("Total Deuda");

        jLabel4.setText("Capital");

        jLabel5.setText("Interés Ordinario");

        totaldeuda.setEditable(false);
        totaldeuda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totaldeuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        capital.setEditable(false);
        capital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        capital.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        interesordinario.setEditable(false);
        interesordinario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        interesordinario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        interesvencido.setEditable(false);
        interesvencido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        interesvencido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        interesvencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesvencidoActionPerformed(evt);
            }
        });

        interesavencer.setEditable(false);
        interesavencer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        interesavencer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        interesavencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesavencerActionPerformed(evt);
            }
        });

        jLabel6.setText("Interés Vencido");

        jLabel7.setText("Interés a Vencer");

        boxcuotas.setText("Pagar todas las Cuotas");
        boxcuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxcuotasActionPerformed(evt);
            }
        });

        boxdescuentos.setText("Aplicar Descuentos por Pagos Adelantados");
        boxdescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxdescuentosActionPerformed(evt);
            }
        });

        totalpago.setEditable(false);
        totalpago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalpago.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel8.setText("Total a Pagar");

        descuentoxpagos.setEditable(false);
        descuentoxpagos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        descuentoxpagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setText("Descuentos x Pagos Adelantados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(interesordinario, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(capital)
                    .addComponent(interesvencido)
                    .addComponent(totaldeuda)
                    .addComponent(interesavencer))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(boxcuotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(boxdescuentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descuentoxpagos)
                    .addComponent(totalpago, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totaldeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxcuotas)
                    .addComponent(totalpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdescuentos)
                    .addComponent(descuentoxpagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(interesordinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interesvencido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interesavencer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jButtonElegir)
                .addGap(35, 35, 35)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonElegir)
                    .addComponent(jButtonCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirActionPerformed
        // TODO add your handling code here:
        String texto = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        Parametros.CODIGO_ELEGIDO = Integer.parseInt(texto);
        Parametros.NOMBRE_ELEGIDO = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        Parametros.RUC_ELEGIDO = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        Parametros.DIRECCION_ELEGIDA = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        dispose();
    }//GEN-LAST:event_jButtonElegirActionPerformed


    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.Buscar.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyPressed
        this.Buscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (Buscar.getText()).toUpperCase();
                Buscar.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (jComboBox1.getSelectedIndex()) {
                    case 0:
                        indiceColumnaTabla = 1;
                        break;//por nombre
                    case 1:
                        indiceColumnaTabla = 2;
                        break;//por ruc
                    case 2:
                        indiceColumnaTabla = 0;
                        break;//por codigo
                }
                repaint();
                filtro(indiceColumnaTabla);
            }
        });
        trsfiltro = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(trsfiltro);
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (evt.getClickCount() > 1) {
            Point point = evt.getPoint();
            int row = jTable1.rowAtPoint(point);
            int column = jTable1.columnAtPoint(point);
            if (column == 11) {
//             setText(String.valueOf(jTable1.getValueAt(fila, 8)));
                //       JOptionPane.showMessageDialog(this, jTable1.getValueAt(row, column));
                this.jTable1.setValueAt(this.jTable1.getValueAt(row, column), row, column + 1);
            }
            sumatoria sumar = new sumatoria();
            Thread HiloSumar = new Thread(sumar);
            HiloSumar.start();
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void interesvencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesvencidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interesvencidoActionPerformed

    private void interesavencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesavencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interesavencerActionPerformed

    private void boxcuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxcuotasActionPerformed
        int totalRow = modelo.getRowCount();
        totalRow -= 1;
        sumatoria = 0.00;
        sumtotal = 0.00;
        if (boxcuotas.isSelected()) { // Si hemos dado clic en el jCheckBox
            for (int i = 0; i <= (totalRow); i++) {
                this.jTable1.setValueAt(this.jTable1.getValueAt(i, 11), i, 12);
                cValorActual = String.valueOf(modelo.getValueAt(i, 12));
                cValorActual = cValorActual.replace(".", "");
                cValorActual = cValorActual.replace(",", ".");
                sumatoria = Double.parseDouble(cValorActual);
                sumtotal += sumatoria;
            }
        } else {
            for (int i = 0; i <= (totalRow); i++) {
                this.jTable1.setValueAt(0, i, 12);
            }
        }
        this.totalpago.setText(formato.format(sumtotal));
    }//GEN-LAST:event_boxcuotasActionPerformed

    private void boxdescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdescuentosActionPerformed
        if (this.boxdescuentos.isSelected()) {
            cDescuentos = this.interesavencer.getText();
            cDescuentos = cDescuentos.replace(".", "").replace(",", ".");
            nDescuentos = Double.parseDouble(cDescuentos);
            nDescuentos = Math.round(nDescuentos * Config.limitedescuento / 100);
            this.descuentoxpagos.setText(formato.format(nDescuentos));
        } else {
            this.descuentoxpagos.setText(formato.format(0));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_boxdescuentosActionPerformed

    public void filtro(int nNumeroColumna) {
        trsfiltro.setRowFilter(RowFilter.regexFilter(Buscar.getText(), nNumeroColumna));
    }

    private void cargarTitulo() {
        modelo.addColumn("Ref.");
        modelo.addColumn("N° Documento");
        modelo.addColumn("Emisión");
        modelo.addColumn("Vence");
        modelo.addColumn("Concepto");
        modelo.addColumn("Nro.");
        modelo.addColumn("Amortización");
        modelo.addColumn("Int. Ordinario");
        modelo.addColumn("Saldo Cuota");
        modelo.addColumn("Int. Moratorio");
        modelo.addColumn("Gastos");
        modelo.addColumn("Total a Pagar");
        modelo.addColumn("Su Pago");
    }

    private void cargarTabla(String sql) {
        double nCapital = 0.00;
        double nMora = 0.00;
        double nInteres = 0.00;
        int nDiaGraciaMora = 0;
        double nImporteGastos, nDiasGracia, nDiasGraciaGastos = 0.00;
        int natraso = 0;
        String catraso = null;

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 

        con = new Conexion();
        stm = con.conectar();
        ResultSet results = null;
        int[] anchos = {5, 80, 80, 80, 60, 60, 80, 80, 80, 80, 80, 80, 80};
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            this.jTable1.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }

        this.jTable1.getColumnModel().getColumn(1).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(5).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(6).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(7).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(8).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(9).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(10).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(11).setCellRenderer(TablaRenderer);
        this.jTable1.getColumnModel().getColumn(12).setCellRenderer(TablaRenderer);

        int cantidadRegistro = modelo.getRowCount();
        for (int i = 1; i <= cantidadRegistro; i++) {
            modelo.removeRow(0);
        }
        try {
            results = stm.executeQuery(sql);
            while (results.next()) {
                // Se crea un array que será una de las filas de la tabla.
                Object[] fila = new Object[13]; // Hay 8 columnas en la tabla
                // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
                //Verificamos si tiene fecha de pago cargado
                //Si tiene fecha de pago
                //usamos como fecha de ultimo pago
                //de lo contrario la fecha de vencimiento
                nImporteGastos = 0.00;
                nCapital = results.getDouble("saldo");
                catraso = results.getString("di");
                nDiasGraciaGastos = Integer.parseInt(results.getString("diasgracia_gastos"));
                if (catraso == null) {
                    natraso = Integer.parseInt(results.getString("atraso"));
                } else {
                    natraso = Integer.parseInt(catraso);
                }
                if (natraso > nDiaGraciaMora) {
                    nInteres = results.getDouble("interesmora");
                    nMora = Math.round(nCapital * ((nInteres / 100) / 360 * natraso));
                    nMora = Math.round(nMora + (nMora * Config.porcentajeiva / 100));
                    fila[9] = formato.format(nMora);
                } else {
                    fila[9] = formato.format(0);
                }

                if (natraso > nDiasGraciaGastos) {
                    nImporteGastos = results.getDouble("gastoscobros");
                    fila[10] = formato.format(nImporteGastos);
                } else {
                    fila[10] = formato.format(0);
                }
                fila[0] = results.getString("creferencia");
                fila[1] = results.getString("documento");
                fila[2] = formatoFecha.format(results.getDate("fecha"));
                fila[3] = formatoFecha.format(results.getDate("vencimiento"));
                fila[4] = results.getString("nomalias");
                fila[5] = formato.format(results.getDouble("cuota"));
                fila[6] = formato.format(results.getDouble("amortiza"));
                fila[7] = formato.format(results.getDouble("minteres"));
                fila[8] = formato.format(results.getDouble("saldo"));
                fila[11] = formato.format(nCapital + nMora + nImporteGastos);
                fila[12] = formato.format(0);
                modelo.addRow(fila);
            }
            this.jTable1.setRowSorter(new TableRowSorter(modelo));
            this.jTable1.updateUI();
            stm.close();
        } catch (SQLException ex2) {
            JOptionPane.showMessageDialog(new JFrame(),
                    "El Sistema No Puede Ingresar a la Consulta de Cuotas",
                    "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex2);
        } catch (Exception ex2) {
            JOptionPane.showMessageDialog(new JFrame(),
                    "El Sistema No Puede Conectarse a la Base de Datos",
                    "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex2);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new cuotas_pendientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JCheckBox boxcuotas;
    private javax.swing.JCheckBox boxdescuentos;
    private javax.swing.JFormattedTextField capital;
    private javax.swing.JTextField codcliente;
    private javax.swing.JFormattedTextField descuentoxpagos;
    private javax.swing.JFormattedTextField interesavencer;
    private javax.swing.JFormattedTextField interesordinario;
    private javax.swing.JFormattedTextField interesvencido;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonElegir;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete2 panelTranslucidoComplete21;
    private javax.swing.JFormattedTextField totaldeuda;
    private javax.swing.JFormattedTextField totalpago;
    // End of variables declaration//GEN-END:variables

    private class ResumenCuenta extends Thread {

        String cSqlResumen = null;

        public void run() {
            con = new Conexion();
            stm = con.conectar();
            ResultSet results = null;
            cSqlResumen = "SELECT SUM(cuenta_clientes.amortiza) AS capital,";
            cSqlResumen += "SUM(cuenta_clientes.minteres) AS interes_ordinario,";
            cSqlResumen += "SUM(cuenta_clientes.saldo) AS totaldeuda,";
            cSqlResumen += "SUM(  IF( DATEDIFF(CURDATE(),vencimiento) <0 ,  cuenta_clientes.minteres, 0 ) ) AS interesnovencido,";
            cSqlResumen += "SUM(  IF( DATEDIFF(CURDATE(),vencimiento) >0,  cuenta_clientes.minteres, 0 ) ) AS interesvencido ";
            cSqlResumen += "FROM cuenta_clientes ";
            cSqlResumen += " WHERE cliente='" + codcliente.getText() + "' ";
            cSqlResumen += " AND saldo>0 ";
            cSqlResumen += " AND moneda=1 ";
            cSqlResumen += " AND comprobante IN(8,9,10)";
            try {
                results = stm.executeQuery(cSqlResumen);
                results.last();
                System.out.println(results.getString("capital"));
                capital.setText(formato.format(results.getDouble("capital")));
                totaldeuda.setText(formato.format(results.getDouble("totaldeuda")));
                interesordinario.setText(formato.format(results.getDouble("interes_ordinario")));
                interesvencido.setText(formato.format(results.getDouble("interesvencido")));
                interesavencer.setText(formato.format(results.getDouble("interesnovencido")));
                stm.close();
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
                System.out.println(ex);
            }

        }
    }

    private class sumatoria extends Thread {

        public void run() {
            ///ESTE PROCEDIMIENTO USAMOS PARA REALIZAR LAS SUMATORIAS DE
            ///CADA CELDA 
            double sumatoria, sumtotal = 0.00;
            String cValorActual = "";
            int totalRow = modelo.getRowCount();
            totalRow -= 1;
            for (int i = 0; i <= (totalRow); i++) {
                //SUMA EL TOTAL DE CHEQUES
                cValorActual = String.valueOf(modelo.getValueAt(i, 12));
                cValorActual = cValorActual.replace(".", "");
                cValorActual = cValorActual.replace(",", ".");
                sumatoria = Double.parseDouble(cValorActual);
                sumtotal += sumatoria;
            }
            totalpago.setText(formato.format(sumtotal));
            //formato.format(sumatoria1);
        }
    }
}
