/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Config;
import Clases.ControlGrabado;
import Clases.ConvertirMayusculas;
import Conexion.Conexion;
import Conexion.Control;
import Conexion.ObtenerFecha;
import DAO.facultadDAO;
import Modelo.Tablas;
import Modelo.facultad;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.openide.util.Exceptions;

/**
 *
 * @author FedeXavier
 */
public class facultades extends javax.swing.JFrame {

    Conexion con = null;
    Statement stm = null;
    Tablas modelo = new Tablas();
    Tablas modelopaises = new Tablas();

    JScrollPane scroll = new JScrollPane();
    private TableRowSorter trsfiltro, trsfiltropais;
    ImageIcon iconograbar = new ImageIcon("src/Iconos/grabar.png");
    ImageIcon iconobuscar = new ImageIcon("src/Iconos/buscar.png");
    ImageIcon icononuevo = new ImageIcon("src/Iconos/nuevo.png");
    ImageIcon iconoeditar = new ImageIcon("src/Iconos/editar.png");
    ImageIcon iconoborrar = new ImageIcon("src/Iconos/eliminar.png");
    ImageIcon iconoprint = new ImageIcon("src/Iconos/impresora.png");
    ImageIcon iconosalir = new ImageIcon("src/Iconos/salir.png");
    ObtenerFecha ODate = new ObtenerFecha();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat formato = new DecimalFormat("#,###.##");
    DecimalFormat formatosinpunto = new DecimalFormat("###");

    /**
     * Creates new form Template
     */
    public facultades() {
        initComponents();
        this.BotonAgregar.setIcon(icononuevo);
        this.BotonEditar.setIcon(iconoeditar);
        this.BotonDelete.setIcon(iconoborrar);
        this.BotonPrint.setIcon(iconoprint);
        this.BotonClose.setIcon(iconosalir);
        this.BotonGrabar.setIcon(iconograbar);
        this.BotonSalir.setIcon(iconosalir);
        this.tablafacultad.setShowGrid(false);
        this.tablafacultad.setOpaque(true);
        this.tablafacultad.setBackground(new Color(102, 204, 255));
        this.tablafacultad.setForeground(Color.BLACK);

        this.setLocationRelativeTo(null); //Centramos el formulario
        this.jTextOpciones1.setVisible(false);
        this.Inicializar();
        this.cargarTitulo();

        GrillaFacultad GrillaOC = new GrillaFacultad();
        Thread HiloGrilla = new Thread(GrillaOC);
        HiloGrilla.start();

    }

    Control hand = new Control();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalle_facultad = new javax.swing.JDialog();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        rector = new javax.swing.JTextField();
        secretario_general = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        decano = new javax.swing.JTextField();
        panel3 = new org.edisoncor.gui.panel.Panel();
        BotonGrabar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonEditar = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonDelete = new javax.swing.JButton();
        BotonPrint = new javax.swing.JButton();
        BotonClose = new javax.swing.JButton();
        jTextOpciones1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafacultad = new javax.swing.JTable();
        panel2 = new org.edisoncor.gui.panel.Panel();
        etiquetacalificadora = new org.edisoncor.gui.label.LabelMetric();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        detalle_facultad.setName("detalle_facultad"); // NOI18N
        detalle_facultad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                detalle_facultadFocusGained(evt);
            }
        });
        detalle_facultad.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                detalle_facultadWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setForeground(new java.awt.Color(255, 0, 0));
        panel1.setToolTipText("");
        panel1.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel1.setName("panel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar Datos de Calificadoras de Riesgo");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        codigo.setEditable(false);
        codigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigo.setEnabled(false);
        codigo.setName("codigo"); // NOI18N

        nombre.setName("nombre"); // NOI18N
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFocusLost(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });

        rector.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rector.setName("rector"); // NOI18N
        rector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rectorFocusLost(evt);
            }
        });
        rector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rectorKeyPressed(evt);
            }
        });

        secretario_general.setName("secretario_general"); // NOI18N
        secretario_general.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                secretario_generalFocusLost(evt);
            }
        });
        secretario_general.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secretario_generalKeyPressed(evt);
            }
        });

        jLabel7.setText("Código");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel9.setText("Nombre");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Rector");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Secretario General");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel4.setText("Decano");
        jLabel4.setName("jLabel4"); // NOI18N

        decano.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        decano.setName("decano"); // NOI18N
        decano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                decanoFocusLost(evt);
            }
        });
        decano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                decanoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(117, 117, 117)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(113, 113, 113)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(secretario_general, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(decano)
                            .addComponent(rector))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secretario_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(180, 180, 180))
        );

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        panel3.setForeground(new java.awt.Color(255, 0, 0));
        panel3.setToolTipText("");
        panel3.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel3.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel3.setName("panel3"); // NOI18N

        BotonGrabar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonGrabar.setText("Grabar");
        BotonGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGrabar.setName("BotonGrabar"); // NOI18N
        BotonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGrabarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.setName("BotonSalir"); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(BotonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGrabar)
                    .addComponent(BotonSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout detalle_facultadLayout = new javax.swing.GroupLayout(detalle_facultad.getContentPane());
        detalle_facultad.getContentPane().setLayout(detalle_facultadLayout);
        detalle_facultadLayout.setHorizontalGroup(
            detalle_facultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detalle_facultadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        detalle_facultadLayout.setVerticalGroup(
            detalle_facultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalle_facultadLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos de Facultades");
        setName("Form"); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setName("jPanel2"); // NOI18N

        BotonEditar.setBackground(new java.awt.Color(255, 255, 255));
        BotonEditar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonEditar.setText("Editar Registro");
        BotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEditar.setName("BotonEditar"); // NOI18N
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonAgregar.setText(" Agregar Registro");
        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.setName("BotonAgregar"); // NOI18N
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonDelete.setBackground(new java.awt.Color(255, 255, 255));
        BotonDelete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonDelete.setText("Eliminar Registro");
        BotonDelete.setToolTipText("");
        BotonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDelete.setName("BotonDelete"); // NOI18N
        BotonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeleteActionPerformed(evt);
            }
        });

        BotonPrint.setBackground(new java.awt.Color(255, 255, 255));
        BotonPrint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonPrint.setText("Listar/Imprimir");
        BotonPrint.setToolTipText("");
        BotonPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPrint.setName("BotonPrint"); // NOI18N
        BotonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrintActionPerformed(evt);
            }
        });

        BotonClose.setBackground(new java.awt.Color(255, 255, 255));
        BotonClose.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BotonClose.setText("     Salir");
        BotonClose.setToolTipText("");
        BotonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonClose.setName("BotonClose"); // NOI18N
        BotonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCloseActionPerformed(evt);
            }
        });

        jTextOpciones1.setEditable(false);
        jTextOpciones1.setName("jTextOpciones1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonPrint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BotonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(jTextOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BotonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(331, Short.MAX_VALUE)
                    .addComponent(jTextOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(245, 245, 245)))
        );

        tablafacultad.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusGained(evt);
            }
        });

        tablafacultad.setModel(modelo);
        tablafacultad.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablafacultad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablafacultad.setName("tablafacultad"); // NOI18N
        tablafacultad.setSelectionBackground(new java.awt.Color(51, 204, 255));
        tablafacultad.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tablafacultad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablafacultadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablafacultadFocusLost(evt);
            }
        });
        tablafacultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablafacultadMouseClicked(evt);
            }
        });
        tablafacultad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablafacultadKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablafacultad);

        panel2.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel2.setColorSecundario(new java.awt.Color(0, 204, 255));
        panel2.setName("panel2"); // NOI18N

        etiquetacalificadora.setText("Facultades");
        etiquetacalificadora.setToolTipText("");
        etiquetacalificadora.setName("etiquetacalificadora"); // NOI18N
        etiquetacalificadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                etiquetacalificadoraMouseMoved(evt);
            }
        });
        etiquetacalificadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetacalificadoraMouseClicked(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Código" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(0, 63, 62));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiquetacalificadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetacalificadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        this.jTextField1.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextField1.getText()).toUpperCase();
                jTextField1.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (jComboBox1.getSelectedIndex()) {
                    case 0:
                        indiceColumnaTabla = 1;
                        break;//por nombre
                    case 1:
                        indiceColumnaTabla = 0;
                        break;//por codigo
                }
                repaint();
                filtro(indiceColumnaTabla);
            }
        });
        trsfiltro = new TableRowSorter(tablafacultad.getModel());
        tablafacultad.setRowSorter(trsfiltro);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed


    private void BotonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCloseActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCloseActionPerformed

    private void Inicializar() {
        Calendar c2 = new GregorianCalendar();
    }

    private void limpiar() {
        this.codigo.setText("0");
        this.nombre.setText("");
        this.rector.setText("");
        this.secretario_general.setText("");
        this.decano.setText("");
    }


    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        codigo.setEnabled(true);
        this.limpiar();
        detalle_facultad.setModal(true);
        detalle_facultad.setSize(625, 318);
        //Establecemos un título para el jDialog
        detalle_facultad.setTitle("Agregar nueva Facultad");
        detalle_facultad.setLocationRelativeTo(null);
        detalle_facultad.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void tablafacultadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablafacultadKeyPressed
        int nFila = this.tablafacultad.getSelectedRow();
        this.jTextOpciones1.setText(this.tablafacultad.getValueAt(nFila, 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tablafacultadKeyPressed

    private void tablafacultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablafacultadMouseClicked
        int nFila = this.tablafacultad.getSelectedRow();
        this.jTextOpciones1.setText(this.tablafacultad.getValueAt(nFila, 0).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tablafacultadMouseClicked

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        this.limpiar();
        if (Integer.valueOf(Config.cNivelUsuario) == 1) {
            int nFila = this.tablafacultad.getSelectedRow();
            if (nFila < 0) {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar un Registro");
                this.tablafacultad.requestFocus();
                return;
            }

            this.codigo.setText(this.tablafacultad.getValueAt(nFila, 0).toString());
            facultadDAO sucDAO = new facultadDAO();
            facultad suc = null;
            try {
                suc = sucDAO.buscarId(Integer.valueOf(this.codigo.getText()));
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
            }
            if (suc != null) {
                nombre.setText(suc.getNombre());
                rector.setText(suc.getRector());
                decano.setText(suc.getDecano());
                secretario_general.setText(suc.getSecretario_general());
                detalle_facultad.setModal(true);
                detalle_facultad.setSize(625, 318);
                //Establecemos un título para el jDialog
                detalle_facultad.setTitle("Modificar Datos de la Facultad");
                detalle_facultad.setLocationRelativeTo(null);
                detalle_facultad.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO NO AUTORIZADO");
            }
        }

        //Envio como parametro el Codigo para saber si voy a modificar
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void tablafacultadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablafacultadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tablafacultadFocusGained

    private void jScrollPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void BotonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeleteActionPerformed
        if (Integer.valueOf(Config.cNivelUsuario) == 1) {
            int nFila = tablafacultad.getSelectedRow();
            String num = tablafacultad.getValueAt(nFila, 0).toString();
            Object[] opciones = {"   Si   ", "   No   "};
            int ret = JOptionPane.showOptionDialog(null, "Desea Eliminar el Registro ? ", "Confirmación", 0, 3, null, opciones, opciones[0]);
            if (ret == 0) {
                facultadDAO sucDAO = new facultadDAO();
                try {
                    facultad suc = sucDAO.buscarId((Integer.valueOf(num)));
                    if (suc == null) {
                        JOptionPane.showMessageDialog(null, "Registro no Existe");
                    } else {
                        sucDAO.eliminarFacultad(Integer.valueOf(num));
                        JOptionPane.showMessageDialog(null, "Registro Eliminado Exitosamente");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no Autorizado");
            }
            GrillaFacultad GrillaOC = new GrillaFacultad();
            Thread HiloGrilla = new Thread(GrillaOC);
            HiloGrilla.start();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDeleteActionPerformed

    private void tablafacultadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablafacultadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tablafacultadFocusLost

    private void BotonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrintActionPerformed
        con = new Conexion();
        stm = con.conectar();
        try {
            Map parameters = new HashMap();
            parameters.put("", new String(""));
            JasperReport jr = null;
            URL url = getClass().getClassLoader().getResource("Reports/sucursales.jasper");
            jr = (JasperReport) JRLoader.loadObject(url);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(jr, null, stm.getConnection());
            JasperViewer ventana = new JasperViewer(masterPrint, false);
            ventana.setTitle("Vista Previa");
            ventana.setVisible(true);
        } catch (Exception e) {
            JDialog.setDefaultLookAndFeelDecorated(true);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_BotonPrintActionPerformed

    private void detalle_facultadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detalle_facultadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_detalle_facultadFocusGained

    private void detalle_facultadWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_detalle_facultadWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_detalle_facultadWindowGainedFocus

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.detalle_facultad.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGrabarActionPerformed
        if (this.nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese del Nombre");
            this.nombre.requestFocus();
            return;
        }

        Object[] opciones = {"   Si   ", "   No   "};
        int ret = JOptionPane.showOptionDialog(null, "Desea Guardar los Datos? ", "Confirmación", 0, 3, null, opciones, opciones[0]);
        if (ret == 0) {

            facultadDAO grabar = new facultadDAO();
            facultad suc = new facultad();

            suc.setNombre(nombre.getText());
            suc.setRector(rector.getText());
            suc.setSecretario_general(secretario_general.getText());
            suc.setDecano(decano.getText());
            try {
                if (Integer.valueOf(codigo.getText()) == 0) {
                    grabar.insertarFacultad(suc);
                } else {
                    suc.setCodigo(Integer.valueOf(codigo.getText()));
                    grabar.actualizarFacultad(suc);
                }
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            }
            detalle_facultad.setVisible(false);
            detalle_facultad.setModal(false);

            GrillaFacultad GrillaOC = new GrillaFacultad();
            Thread HiloGrilla = new Thread(GrillaOC);
            HiloGrilla.start();
        }
    }//GEN-LAST:event_BotonGrabarActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.rector.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyPressed

    private void rectorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rectorKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.decano.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.nombre.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rectorKeyPressed

    private void secretario_generalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secretario_generalKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.BotonGrabar.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.decano.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_secretario_generalKeyPressed

    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        String letras = ConvertirMayusculas.cadena(nombre);
        nombre.setText(letras);
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFocusLost

    private void decanoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decanoKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.secretario_general.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.rector.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_decanoKeyPressed

    private void etiquetacalificadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetacalificadoraMouseClicked

    }//GEN-LAST:event_etiquetacalificadoraMouseClicked

    private void etiquetacalificadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetacalificadoraMouseMoved

    }//GEN-LAST:event_etiquetacalificadoraMouseMoved

    private void rectorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rectorFocusLost
        String letras = ConvertirMayusculas.cadena(rector);
        rector.setText(letras);
        // TODO add your handling code here:
    }//GEN-LAST:event_rectorFocusLost

    private void decanoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_decanoFocusLost
        String letras = ConvertirMayusculas.cadena(decano);
        decano.setText(letras);
        // TODO add your handling code here:
    }//GEN-LAST:event_decanoFocusLost

    private void secretario_generalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secretario_generalFocusLost
        String letras = ConvertirMayusculas.cadena(secretario_general);
        secretario_general.setText(letras);
        // TODO add your handling code here:
    }//GEN-LAST:event_secretario_generalFocusLost

    public void filtro(int nNumeroColumna) {
        trsfiltro.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), nNumeroColumna));
    }

    private void cargarTitulo() {
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Rector");
        modelo.addColumn("Decano");
        modelo.addColumn("Secretario General");
        int[] anchos = {90, 150, 250, 250, 250};
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            tablafacultad.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablafacultad.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablafacultad.getTableHeader().setFont(new Font("Arial Black", 1, 11));

        Font font = new Font("Arial", Font.BOLD, 10);
        this.tablafacultad.setFont(font);

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer AlinearCentro = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        AlinearCentro.setHorizontalAlignment(SwingConstants.CENTER);
        this.tablafacultad.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {    //</editor-fold>
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facultades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonClose;
    private javax.swing.JButton BotonDelete;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonGrabar;
    private javax.swing.JButton BotonPrint;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField decano;
    private javax.swing.JDialog detalle_facultad;
    private org.edisoncor.gui.label.LabelMetric etiquetacalificadora;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextOpciones1;
    private javax.swing.JTextField nombre;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField rector;
    private javax.swing.JTextField secretario_general;
    private javax.swing.JTable tablafacultad;
    // End of variables declaration//GEN-END:variables

    private class GrillaFacultad extends Thread {

        public void run() {

            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
            int cantidadRegistro = modelo.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelo.removeRow(0);
            }

            facultadDAO DAO = new facultadDAO();
            try {
                for (facultad suc : DAO.todos()) {
                    String Datos[] = {String.valueOf(suc.getCodigo()), suc.getNombre(), suc.getRector(), suc.getDecano(), suc.getSecretario_general()};
                    modelo.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablafacultad.setRowSorter(new TableRowSorter(modelo));
            int cantFilas = tablafacultad.getRowCount();
            if (cantFilas > 0) {
                BotonEditar.setEnabled(true);
                BotonDelete.setEnabled(true);
                BotonPrint.setEnabled(true);
            } else {
                BotonEditar.setEnabled(false);
                BotonDelete.setEnabled(false);
                BotonPrint.setEnabled(false);
            }
        }
    }

}
