/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

import Clases.calculateXIRR;
import Conexion.Conexion;
import Conexion.ObtenerFecha;
import DAO.configuracionDAO;
import DAO.detalle_cupones_titulosDAO;
import DAO.tituloDAO;
import Modelo.FlujoVencimientos;
import java.sql.Date;
import Modelo.Tablas;
import Modelo.configuracion;
import Modelo.detalle_cupones_titulos;
import Modelo.titulo;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static org.apache.poi.hssf.usermodel.HeaderFooter.date;
import static org.joda.time.format.ISODateTimeFormat.date;
import org.openide.util.Exceptions;

/**
 *
 * @author faisc
 */
public class flujo_de_inversion extends javax.swing.JFrame {

    Conexion con = null;
    Statement stm = null;

    ImageIcon iconobuscar = new ImageIcon("src/Iconos/buscar.png");
    Tablas modelo = new Tablas();
    Tablas modelotitulo = new Tablas();
    ObtenerFecha ODate = new ObtenerFecha();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatoFecha2 = new SimpleDateFormat("yyyy,MM,dd");
    DecimalFormat formato = new DecimalFormat("#,###.##");
    Calendar c2 = new GregorianCalendar();
    private TableRowSorter trsfiltrotitulo;
    DecimalFormat formatea = new DecimalFormat("###,###.##");

    /**
     * Creates new form flujo_de_inversion
     */
    public flujo_de_inversion() {
        initComponents();
        this.buscartitulo.setIcon(iconobuscar);
        this.setLocationRelativeTo(null); //Centramos el formulario
        this.Inicializar();
        this.cargarTituloTabla();
        this.TitTitulo();
        this.cupones.setVisible(false);
        this.base.setVisible(false);
        this.codmoneda.setVisible(false);
        this.titulo.setVisible(false);

        CargarTitulos grillati = new CargarTitulos();
        Thread hiloti = new Thread(grillati);
        hiloti.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTitulos = new javax.swing.JDialog();
        jPanel21 = new javax.swing.JPanel();
        combotitulo = new javax.swing.JComboBox();
        txtbuscartitulo = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablatitulo = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        AceptarCasa = new javax.swing.JButton();
        SalirCasa = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacupones = new javax.swing.JTable();
        panel1 = new org.edisoncor.gui.panel.Panel();
        etiquetavacaciones = new org.edisoncor.gui.label.LabelMetric();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isin = new javax.swing.JTextField();
        dEmision = new com.toedter.calendar.JDateChooser();
        serie = new javax.swing.JTextField();
        dVence = new com.toedter.calendar.JDateChooser();
        dCompra = new com.toedter.calendar.JDateChooser();
        precio = new javax.swing.JFormattedTextField();
        valornominal = new javax.swing.JFormattedTextField();
        inversion = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        buscartitulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        moneda = new javax.swing.JTextField();
        dUltimoCupon = new com.toedter.calendar.JDateChooser();
        pagos = new javax.swing.JTextField();
        tasa = new javax.swing.JFormattedTextField();
        capital = new javax.swing.JTextField();
        base = new javax.swing.JFormattedTextField();
        codmoneda = new javax.swing.JFormattedTextField();
        cupones = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dFechaOperacion = new com.toedter.calendar.JDateChooser();
        valornominal_flujo = new javax.swing.JFormattedTextField();
        precioclean_flujo = new javax.swing.JFormattedTextField();
        comision = new javax.swing.JFormattedTextField();
        arancel = new javax.swing.JFormattedTextField();
        bGenerar = new javax.swing.JButton();
        titulo = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        porcentajetir = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        meses_restantes = new javax.swing.JFormattedTextField();
        totalintereses = new javax.swing.JFormattedTextField();
        total_a_recibir = new javax.swing.JFormattedTextField();
        comision_intermediacion = new javax.swing.JFormattedTextField();
        arancelbursatil = new javax.swing.JFormattedTextField();
        montoiva = new javax.swing.JFormattedTextField();
        totalgastos = new javax.swing.JFormattedTextField();
        BImprimir = new javax.swing.JButton();

        BTitulos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        BTitulos.setTitle(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.BTitulos.title")); // NOI18N

        jPanel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combotitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        combotitulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar por Título", "Buscar por Código", "Buscar por Emisor" }));
        combotitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combotitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotituloActionPerformed(evt);
            }
        });

        txtbuscartitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbuscartitulo.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.txtbuscartitulo.text")); // NOI18N
        txtbuscartitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscartituloActionPerformed(evt);
            }
        });
        txtbuscartitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscartituloKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(combotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbuscartitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscartitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tablatitulo.setModel(modelotitulo        );
        tablatitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablatituloMouseClicked(evt);
            }
        });
        tablatitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablatituloKeyPressed(evt);
            }
        });
        jScrollPane8.setViewportView(tablatitulo);

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AceptarCasa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AceptarCasa.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.AceptarCasa.text")); // NOI18N
        AceptarCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCasaActionPerformed(evt);
            }
        });

        SalirCasa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SalirCasa.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.SalirCasa.text")); // NOI18N
        SalirCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(AceptarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(SalirCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarCasa)
                    .addComponent(SalirCasa))
                .addContainerGap())
        );

        javax.swing.GroupLayout BTitulosLayout = new javax.swing.GroupLayout(BTitulos.getContentPane());
        BTitulos.getContentPane().setLayout(BTitulosLayout);
        BTitulosLayout.setHorizontalGroup(
            BTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTitulosLayout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BTitulosLayout.setVerticalGroup(
            BTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTitulosLayout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablacupones.setModel(modelo);
        jScrollPane1.setViewportView(tablacupones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.setColorPrimario(new java.awt.Color(102, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 204, 255));

        etiquetavacaciones.setBackground(new java.awt.Color(255, 255, 255));
        etiquetavacaciones.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.etiquetavacaciones.text")); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(etiquetavacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(etiquetavacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel8.text")); // NOI18N

        isin.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.isin.text")); // NOI18N
        isin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        isin.setEnabled(false);

        dEmision.setEnabled(false);
        dEmision.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dEmisionFocusGained(evt);
            }
        });

        serie.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.serie.text")); // NOI18N
        serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieActionPerformed(evt);
            }
        });

        dVence.setEnabled(false);
        dVence.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dVenceFocusGained(evt);
            }
        });

        dCompra.setEnabled(false);
        dCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dCompraFocusGained(evt);
            }
        });

        precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precio.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.precio.text")); // NOI18N
        precio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        precio.setEnabled(false);
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        valornominal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        valornominal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valornominal.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.valornominal.text")); // NOI18N
        valornominal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        valornominal.setEnabled(false);

        inversion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        inversion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inversion.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.inversion.text")); // NOI18N
        inversion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inversion.setEnabled(false);
        inversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversionActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel3.text")); // NOI18N

        buscartitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscartitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscartituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dVence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inversion)
                            .addComponent(serie)
                            .addComponent(dEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precio)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(valornominal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscartitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(isin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscartitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dVence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valornominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel10.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel11.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel12.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel13.text")); // NOI18N

        moneda.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.moneda.text")); // NOI18N
        moneda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        moneda.setEnabled(false);

        dUltimoCupon.setEnabled(false);
        dUltimoCupon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dUltimoCuponFocusGained(evt);
            }
        });

        pagos.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.moneda.text")); // NOI18N
        pagos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        pagos.setEnabled(false);

        tasa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tasa.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.tasa.text")); // NOI18N
        tasa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tasa.setEnabled(false);

        capital.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.moneda.text")); // NOI18N
        capital.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        capital.setEnabled(false);

        base.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        base.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.base.text")); // NOI18N

        codmoneda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        codmoneda.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.codmoneda.text")); // NOI18N

        cupones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cupones.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.cupones.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(cupones, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagos)
                                    .addComponent(moneda)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(capital))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codmoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dUltimoCupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tasa)
                                        .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 37, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(dUltimoCupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codmoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel14.text")); // NOI18N

        jLabel15.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel15.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel16.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel17.text")); // NOI18N

        jLabel18.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel18.text")); // NOI18N

        dFechaOperacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dFechaOperacionFocusGained(evt);
            }
        });

        valornominal_flujo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        valornominal_flujo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valornominal_flujo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valornominal_flujoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valornominal_flujoFocusLost(evt);
            }
        });
        valornominal_flujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valornominal_flujoActionPerformed(evt);
            }
        });
        valornominal_flujo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valornominal_flujoKeyPressed(evt);
            }
        });

        precioclean_flujo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        precioclean_flujo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioclean_flujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioclean_flujoActionPerformed(evt);
            }
        });
        precioclean_flujo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioclean_flujoKeyPressed(evt);
            }
        });

        comision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        comision.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        comision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comisionKeyPressed(evt);
            }
        });

        arancel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        arancel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        arancel.setEnabled(false);

        bGenerar.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.bGenerar.text")); // NOI18N
        bGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarActionPerformed(evt);
            }
        });

        titulo.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.titulo.text")); // NOI18N

        porcentajetir.setEditable(false);
        porcentajetir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        porcentajetir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        porcentajetir.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.porcentajetir.text")); // NOI18N

        jLabel26.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel26.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel26))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dFechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valornominal_flujo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(precioclean_flujo)
                            .addComponent(comision)
                            .addComponent(arancel)
                            .addComponent(porcentajetir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(dFechaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(valornominal_flujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(precioclean_flujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addComponent(arancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentajetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bGenerar))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel19.text")); // NOI18N

        jLabel20.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel20.text")); // NOI18N

        jLabel21.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel21.text")); // NOI18N

        jLabel22.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel22.text")); // NOI18N

        jLabel23.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel23.text")); // NOI18N

        jLabel24.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel24.text")); // NOI18N

        jLabel25.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.jLabel25.text")); // NOI18N

        meses_restantes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        meses_restantes.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.meses_restantes.text")); // NOI18N
        meses_restantes.setEnabled(false);

        totalintereses.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalintereses.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalintereses.setEnabled(false);
        totalintereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalinteresesActionPerformed(evt);
            }
        });

        total_a_recibir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        total_a_recibir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_a_recibir.setEnabled(false);
        total_a_recibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_a_recibirActionPerformed(evt);
            }
        });

        comision_intermediacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        comision_intermediacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        comision_intermediacion.setEnabled(false);
        comision_intermediacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comision_intermediacionActionPerformed(evt);
            }
        });

        arancelbursatil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        arancelbursatil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        arancelbursatil.setEnabled(false);
        arancelbursatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arancelbursatilActionPerformed(evt);
            }
        });

        montoiva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        montoiva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        montoiva.setEnabled(false);
        montoiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoivaActionPerformed(evt);
            }
        });

        totalgastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalgastos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalgastos.setEnabled(false);
        totalgastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalgastosActionPerformed(evt);
            }
        });

        BImprimir.setText(org.openide.util.NbBundle.getMessage(flujo_de_inversion.class, "flujo_de_inversion.BImprimir.text")); // NOI18N
        BImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(meses_restantes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalgastos, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(montoiva)
                            .addComponent(arancelbursatil)
                            .addComponent(comision_intermediacion)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_a_recibir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(67, 67, 67)
                        .addComponent(totalintereses, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(meses_restantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(totalintereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(total_a_recibir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(comision_intermediacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(arancelbursatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(montoiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(totalgastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BImprimir)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inicializar() {
        this.isin.setText("");
        this.serie.setText("");
        this.dEmision.setCalendar(c2);
        this.dVence.setCalendar(c2);
        this.dCompra.setCalendar(c2);
        this.precio.setText("0");
        this.valornominal.setText("0");
        this.inversion.setText("0");
        this.moneda.setText("");
        this.pagos.setText("");
        this.capital.setText("");
        this.tasa.setText("0");
        this.dUltimoCupon.setCalendar(c2);
        this.dFechaOperacion.setCalendar(c2);
        this.valornominal_flujo.setText("0");
        this.precioclean_flujo.setText("0");
        this.comision.setText("0");
        this.arancel.setText("0");
    }

    private void cargarTituloTabla() {
        modelo.addColumn("Tipo");
        modelo.addColumn("N° Cupón");
        modelo.addColumn("Vencimiento");
        modelo.addColumn("Monto");
        modelo.addColumn("Fecha");
        // 0    1   2     3   
        int[] anchos = {100, 100, 100, 100, 1};
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            tablacupones.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablacupones.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablacupones.getTableHeader().setFont(new Font("Arial Black", 1, 9));

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer AlinearCentro = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        AlinearCentro.setHorizontalAlignment(SwingConstants.CENTER);
        this.tablacupones.getColumnModel().getColumn(1).setCellRenderer(TablaRenderer);
        this.tablacupones.getColumnModel().getColumn(2).setCellRenderer(AlinearCentro);
        this.tablacupones.getColumnModel().getColumn(3).setCellRenderer(TablaRenderer);
    }

    private void TitTitulo() {
        modelotitulo.addColumn("Código");
        modelotitulo.addColumn("Nombre");
        modelotitulo.addColumn("Emisor");

        int[] anchos = {90, 100, 150};
        for (int i = 0; i < modelotitulo.getColumnCount(); i++) {
            tablatitulo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        ((DefaultTableCellRenderer) tablatitulo.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// Este código es para centrar las cabeceras de la tabla.
        tablatitulo.getTableHeader().setFont(new Font("Arial Black", 1, 10));

        // Hacemos Invisible la Celda de Costos de los Productos
        Font font = new Font("Arial", Font.BOLD, 9);
        this.tablatitulo.setFont(font);

        DefaultTableCellRenderer TablaRenderer = new DefaultTableCellRenderer();
        TablaRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // aqui defines donde alinear 
        this.tablatitulo.getColumnModel().getColumn(0).setCellRenderer(TablaRenderer);
    }

    public void sumarinteres() {
        ///ESTE PROCEDIMIENTO USAMOS PARA REALIZAR LAS SUMATORIAS DE
        ///CADA CELDA 
        double suMonto = 0.00;

        String cMonto = "";

        int totalRow = tablacupones.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            //SUMA EL TOTAL A PAGAR
            cMonto = String.valueOf(tablacupones.getValueAt(i, 3));
            cMonto = cMonto.replace(".", "").replace(",", ".");
            suMonto += Double.valueOf(cMonto);
        }
        //LUEGO RESTAMOS AL VALOR NETO A ENTREGAR
        this.totalintereses.setText(formatea.format(suMonto));
        //formato.format(sumatoria1);
    }


    private void dEmisionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dEmisionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dEmisionFocusGained

    private void dVenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dVenceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dVenceFocusGained

    private void serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieActionPerformed
        tituloDAO titDAO = new tituloDAO();
        titulo tit = null;
        try {
            tit = titDAO.buscarString(this.serie.getText());
            if (tit.getNomalias() == null) {
                BTitulos.setModal(true);
                BTitulos.setSize(482, 575);
                BTitulos.setLocationRelativeTo(null);
                BTitulos.setTitle("Buscar Título");
                BTitulos.setVisible(true);
                moneda.requestFocus();
                BTitulos.setModal(false);
            } else {
                /*        emisor.setText(String.valueOf(tit.getEmpresa().getCodigo()));
                nombreemisor.setText(tit.getEmpresa().getNombre().trim());
                nombretitulo.setText(tit.getNomalias().trim());
                moneda.setText(String.valueOf(tit.getMoneda().getCodigo()));
                nombremoneda.setText(tit.getMoneda().getNombre());
                tasa.setText(formatea.format(tit.getTasa()));
                base.setText(formatea.format(tit.getBase()));
                fechaemision.setDate(tit.getFechaemision());
                vencimiento.setDate(tit.getVencimiento());
                cupones.setText(String.valueOf(tit.getCupones()));
                String cPeriodoPago = tit.getPagointeres().toString();

                //MENSUAL, BIMESTRAL, TRIMESTRAL, CUATRIMESTRAL, SEMESTRAL, ANUAL, VENCIMIENTO
                if (cPeriodoPago.toUpperCase().equals("MENSUAL")) {
                    periodopago.setSelectedIndex(0);
                } else if (cPeriodoPago.toUpperCase().equals("MENSUAL")) {
                    periodopago.setSelectedIndex(1);
                } else if (cPeriodoPago.toUpperCase().equals("TRIMESTRAL")) {
                    periodopago.setSelectedIndex(2);
                } else if (cPeriodoPago.toUpperCase().equals("CUATRIMESTRAL")) {
                    periodopago.setSelectedIndex(3);
                } else if (cPeriodoPago.toUpperCase().equals("SEMESTRAL")) {
                    periodopago.setSelectedIndex(4);
                } else if (cPeriodoPago.toUpperCase().equals("ANUAL")) {
                    periodopago.setSelectedIndex(5);
                } else if (cPeriodoPago.toUpperCase().equals("VENCIMIENTO")) {
                    periodopago.setSelectedIndex(6);
                }*/
                //Establecemos un título para el jDialog
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        moneda.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_serieActionPerformed

    private void dCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dCompraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dCompraFocusGained

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void inversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionActionPerformed

    private void dUltimoCuponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dUltimoCuponFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dUltimoCuponFocusGained

    private void buscartituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscartituloActionPerformed
        BTitulos.setModal(true);
        BTitulos.setSize(482, 575);
        BTitulos.setLocationRelativeTo(null);
        BTitulos.setTitle("Buscar Título");
        BTitulos.setVisible(true);
        moneda.requestFocus();
        BTitulos.setModal(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buscartituloActionPerformed

    private void combotituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotituloActionPerformed

    private void txtbuscartituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscartituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscartituloActionPerformed

    private void txtbuscartituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscartituloKeyPressed
        this.txtbuscartitulo.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtbuscartitulo.getText()).toUpperCase();
                txtbuscartitulo.setText(cadena);
                int indiceColumnaTabla = 0;
                switch (combotitulo.getSelectedIndex()) {
                    case 0:
                        indiceColumnaTabla = 1;
                        break;//por nombre
                    case 1:
                        indiceColumnaTabla = 0;
                    case 2:
                        indiceColumnaTabla = 2;
                }
                repaint();
                filtrotitulo(indiceColumnaTabla);
            }
        });
        trsfiltrotitulo = new TableRowSorter(tablatitulo.getModel());
        tablatitulo.setRowSorter(trsfiltrotitulo);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscartituloKeyPressed

    public void filtrotitulo(int nNumeroColumna) {
        trsfiltrotitulo.setRowFilter(RowFilter.regexFilter(this.txtbuscartitulo.getText(), nNumeroColumna));
    }


    private void tablatituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablatituloMouseClicked
        this.AceptarCasa.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablatituloMouseClicked

    private void tablatituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablatituloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.AceptarCasa.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablatituloKeyPressed

    private void AceptarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCasaActionPerformed
        int nFila = this.tablatitulo.getSelectedRow();
        this.serie.setText(this.tablatitulo.getValueAt(nFila, 1).toString());
//        this.nombretitulo.setText(this.tablatitulo.getValueAt(nFila, 1).toString());
        configuracionDAO configDAO = new configuracionDAO();
        configuracion config = null;
        config = configDAO.configBursatil();
        System.out.println("ARANCEL " + config.getArancelrentafija());

        tituloDAO titDAO = new tituloDAO();
        titulo tit = null;
        try {
            tit = titDAO.buscarString(this.serie.getText());
            moneda.setText(String.valueOf(tit.getMoneda().getNombre().trim()));
            codmoneda.setText(formato.format(tit.getMoneda().getCodigo()));
            tasa.setText(formatea.format(tit.getTasa()));
            titulo.setText(formatea.format(tit.getCodigo()));
            dEmision.setDate(tit.getFechaemision());
            dVence.setDate(tit.getVencimiento());
            pagos.setText(tit.getPagointeres());
            base.setText(formato.format(tit.getBase()));
            isin.setText(tit.getEmpresa().getNomalias());
            arancel.setText(formato.format(config.getArancelrentafija()));
            valornominal_flujo.setText(formato.format(tit.getCorte_minimo()));
            cupones.setText(formato.format(tit.getCupones()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }

        this.BTitulos.setVisible(false);
        this.txtbuscartitulo.setText("");
        this.dFechaOperacion.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarCasaActionPerformed

    private void SalirCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCasaActionPerformed
        this.BTitulos.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirCasaActionPerformed

    private void dFechaOperacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dFechaOperacionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dFechaOperacionFocusGained

    private void dFormatoFecha(String inputDate) {

        // Definir el formato de entrada
        DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Definir el formato de salida
        DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy, MM, dd");

        try {
            // Convertir la cadena de entrada a un objeto LocalDate
            LocalDate date = LocalDate.parse(inputDate, inputFormatter);

            // Convertir el objeto LocalDate al formato de salida deseado
            String outputDate = date.format(outputFormatter);

            System.out.println("Fecha en nuevo formato: " + outputDate);
        } catch (DateTimeParseException e) {
            System.err.println("Formato de fecha no válido: " + inputDate);
        }
    }


    private void bGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarActionPerformed

        //LIMPIO CAMPOS Y LUEGO CALCULO INTERESES
        valornominal.setText("0");
        inversion.setText("0");
        precio.setText("0");
        String cPrecio = precioclean_flujo.getText();
        cPrecio = cPrecio.replace(".", "").replace(",", ".");

        String cValorNominal = valornominal_flujo.getText();
        cValorNominal = cValorNominal.replace(".", "").replace(",", ".");

        valornominal.setText(this.valornominal_flujo.getText());
        precio.setText(this.precioclean_flujo.getText());
        cValorNominal = this.valornominal.getText();
        cValorNominal = cValorNominal.replace(".", "").replace(",", ".");
        cPrecio = this.precioclean_flujo.getText();
        cPrecio = cPrecio.replace(".", "").replace(",", ".");
        this.inversion.setText(formato.format(Double.valueOf(cValorNominal) * Double.valueOf(cPrecio) / 100));

        //SE CALCULA EL ARANCEL BURSATIL, AUN SIN IVA
        String cInversion = this.inversion.getText();
        cInversion = cInversion.replace(".", "").replace(",", ".");
        String cArancel = this.arancel.getText();
        cArancel = cArancel.replace(".", "").replace(",", ".");
        //SE OBTIENE VALOR DE COMISION
        String cComision = this.comision.getText();
        cComision = cComision.replace(".", "").replace(",", ".");

        int cantidadRegistro = modelo.getRowCount();

        String cNombreDia = "SD";

        String cTasa = tasa.getText();
        cTasa = cTasa.replace(".", "").replace(",", ".");
        double nTasa = Double.valueOf(cTasa);
        double nValorCupon = 0.00;
        int nbase = 0;

        double nValorInversion = 0.00;
        if (Integer.valueOf(base.getText()) == 1) {
            nbase = 360;
        } else {
            nbase = 365;
        }

        for (int i = 1; i <= cantidadRegistro; i++) {
            modelo.removeRow(0);
        }
        int nCantidad = 0;
        detalle_cupones_titulosDAO detDAO = new detalle_cupones_titulosDAO();
        try {
            String ValorInicial[] = {"MONTO INV.", "0", formatoFecha.format(this.dCompra.getDate()), formato.format(Double.valueOf(cInversion) * -1), formatoFecha2.format(this.dCompra.getDate())};
            modelo.addRow(ValorInicial);

            for (detalle_cupones_titulos detvta : detDAO.MostrarxTituloTodos(Integer.valueOf(titulo.getText()))) {
                LocalDate currenDate = LocalDate.parse(detvta.getFechavencimiento().toString());
                int diaSemana = currenDate.getDayOfWeek().getValue() + 1;
                switch (diaSemana) {
                    case 1:
                        cNombreDia = "Domingo";
                        break; // break es opcional
                    case 2:
                        cNombreDia = "Lunes";
                        break; // break es opcional
                    case 3:
                        cNombreDia = "Martes";
                        break; // break es opcional
                    case 4:
                        cNombreDia = "Míercoles";
                        break; // break es opcional
                    case 5:
                        cNombreDia = "Jueves";
                        break; // break es opcional
                    case 6:
                        cNombreDia = "Viernes";
                        break; // break es opcional
                    case 7:
                        cNombreDia = "Sábado";
                        break; // break es opcional
                }
                if (Integer.valueOf(codmoneda.getText()) == 1) {
                    nValorInversion = Math.round(Double.valueOf(cValorNominal));
                    nValorCupon = Math.round((nValorInversion * (nTasa / 100) * detvta.getPlazo()) / nbase);
                } else {
                    nValorInversion = Double.valueOf(cValorNominal);
                    nValorCupon = (nValorInversion * (nTasa / 100) * detvta.getPlazo()) / nbase;
                }
                //EL CUPON PASA A CERO SI ES QUE YA VENCIÓ
                if (detvta.getEstadocupon() <= 0) {
                    nValorCupon = 0;
                }
                String Detalle[] = {"CUPÓN", formatea.format(detvta.getNumerocupon()),
                    formatoFecha.format(detvta.getFechavencimiento()), formatea.format(nValorCupon), detvta.getFormatofecha()};
                modelo.addRow(Detalle);
            }

            String ValorFinal[] = {"CAPITAL", "0", formatoFecha.format(this.dVence.getDate()),
                formato.format(Double.valueOf(cValorNominal)), formatoFecha2.format(this.dVence.getDate())};
            modelo.addRow(ValorFinal);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }

        if (Integer.valueOf(this.codmoneda.getText()) == 1) {
            this.arancelbursatil.setText(formato.format(Math.round(Double.valueOf(cInversion) * Double.valueOf(cArancel)) / 100));
            this.comision_intermediacion.setText(formato.format(Math.round(Double.valueOf(cInversion) * Double.valueOf(cComision)) / 100));
        } else {
            this.arancelbursatil.setText(formato.format(Double.valueOf(cInversion) * Double.valueOf(cArancel) / 100));
            this.comision_intermediacion.setText(formato.format(Double.valueOf(cInversion) * Double.valueOf(cComision) / 100));
        }
        String cImporteArancel = this.arancelbursatil.getText();
        cImporteArancel = cImporteArancel.replace(".", "").replace(",", ".");
        String cImporteComision = this.comision_intermediacion.getText();
        cImporteComision = cImporteComision.replace(".", "").replace(",", ".");

        double nTotalIva = 0.00;
        if (Integer.valueOf(this.codmoneda.getText()) == 1) {
            nTotalIva = Math.round((Double.valueOf(cImporteArancel) + Double.valueOf(cImporteComision)) * 10 / 100);
        } else {
            nTotalIva = (Double.valueOf(cImporteArancel) + Double.valueOf(cImporteComision)) * 10 / 100;
        }
        this.montoiva.setText(formato.format(nTotalIva));
        this.totalgastos.setText(formato.format(Double.valueOf(cImporteArancel) + Double.valueOf(cImporteComision) + nTotalIva));
        this.sumarinteres();
        this.cargarValoresTir();
        // TODO add your handling code here:
    }//GEN-LAST:event_bGenerarActionPerformed

    private void cargarValoresTir() {

        int rowCount = modelo.getRowCount();
        double[] cashFlows = new double[rowCount];
        LocalDate[] dates = new LocalDate[rowCount];
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Lista para almacenar las fechas convertidas
        for (int i = 0; i < rowCount; i++) {
            String cImporte = String.valueOf(tablacupones.getValueAt(i, 3));
            cImporte = cImporte.replace(".", "").replace(",", ".");
            cashFlows[i] = Double.valueOf(cImporte);
            //String dateString = (String) tablacupones.getValueAt(i, 4);
            try {
                // Parsear la fecha y crear el objeto LocalDate
                String fecha = (String) tablacupones.getValueAt(i, 4);
                String[] partes = fecha.split(",");

                String anio = partes[0]; // "2024"
                String mes = partes[1];  // "10"
                String dia = partes[2];  // "14"                    
                LocalDate date = LocalDate.of(Integer.valueOf(anio), Integer.valueOf(mes), Integer.valueOf(dia));
                dates[i] = date; // Almacenar el objeto LocalDate

            } catch (DateTimeParseException e) {
                dates[i] = null; // Manejar el error
            }
        }


        try {
            calculateXIRR calcular = new calculateXIRR();
            double tir = calcular.calculateXIRR(cashFlows, dates);
            this.porcentajetir.setText(formato.format(tir * 100));
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }


    private void precioclean_flujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioclean_flujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioclean_flujoActionPerformed

    private void valornominal_flujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valornominal_flujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valornominal_flujoActionPerformed

    private void valornominal_flujoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valornominal_flujoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valornominal_flujoFocusGained

    private void valornominal_flujoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valornominal_flujoKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.precioclean_flujo.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_valornominal_flujoKeyPressed

    private void precioclean_flujoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioclean_flujoKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == KeyEvent.VK_DOWN) { //Si pulso enter o cursor abajo obtiene el foco el sgte objeto
            this.comision.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.valornominal_flujo.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_precioclean_flujoKeyPressed

    private void comisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comisionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            this.precioclean_flujo.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_comisionKeyPressed

    private void valornominal_flujoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valornominal_flujoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valornominal_flujoFocusLost

    private void total_a_recibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_a_recibirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_a_recibirActionPerformed

    private void comision_intermediacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comision_intermediacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comision_intermediacionActionPerformed

    private void arancelbursatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arancelbursatilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arancelbursatilActionPerformed

    private void totalgastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalgastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalgastosActionPerformed

    private void montoivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoivaActionPerformed

    private void totalinteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalinteresesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalinteresesActionPerformed

    private void BImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BImprimirActionPerformed

        int nFila = 0;
        List Resultados = new ArrayList();
        FlujoVencimientos flujo;
        String cMonto = "0";

        Date FechaCompra = ODate.de_java_a_sql(dCompra.getDate());

        for (nFila = 0; nFila < tablacupones.getRowCount(); nFila++) {

            cMonto = tablacupones.getValueAt(nFila, 3).toString();
            cMonto = cMonto.replace(".", "").replace(",", ".");

            flujo = new FlujoVencimientos(tablacupones.getValueAt(nFila, 0).toString(),
                    tablacupones.getValueAt(nFila, 1).toString(),
                    tablacupones.getValueAt(nFila, 2).toString(),
                    Double.valueOf(cMonto));
            Resultados.add(flujo);
            cMonto = "0";
        }

        try {
            Map parameters = new HashMap();
            //Ahora que hay parametros le enviamos uno con el mismo nombre del que creamos
            String cMontoNominal = valornominal.getText();
            cMontoNominal = cMontoNominal.replace(".", "").replace(",", ".");

            String cMontoInversion = inversion.getText();
            cMontoInversion = cMontoInversion.replace(".", "").replace(",", ".");

            String cPrecio = precio.getText();
            cPrecio = cPrecio.replace(",", ".");
            String cTasa = tasa.getText();

            parameters.put("cSerie", serie.getText().trim());
            parameters.put("cMoneda", moneda.getText().trim());
            parameters.put("cPagos", pagos.getText().trim());
            parameters.put("cIsin", isin.getText().trim());
            parameters.put("cTasa", tasa.getText());
            parameters.put("dFecha", FechaCompra);
            parameters.put("nMontoNominal", Double.valueOf(cMontoNominal));
            parameters.put("nMontoInversion", Double.valueOf(cMontoInversion));
            parameters.put("nPrecio", Double.valueOf(cPrecio));

            JasperReport jr = null;

            URL url = getClass().getClassLoader().getResource("Reports/flujo_inversion.jasper");
            jr = (JasperReport) JRLoader.loadObject(url);// Libro_Iva_Venta.jasper
            JasperPrint masterPrint = null;
            //Se le incluye el parametro con el nombre parameters porque asi lo definimos
            masterPrint = JasperFillManager.fillReport(jr, parameters, new JRBeanCollectionDataSource(Resultados));
            JasperViewer ventana = new JasperViewer(masterPrint, false);
            ventana.setTitle("Vista Previa");
            ventana.setVisible(true);
        } catch (Exception e) {
            JDialog.setDefaultLookAndFeelDecorated(true);
            JOptionPane.showMessageDialog(null, e, "Error", 1);
            System.out.println(e);
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {    //</editor-fold>
        }        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flujo_de_inversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCasa;
    private javax.swing.JButton BImprimir;
    private javax.swing.JDialog BTitulos;
    private javax.swing.JButton SalirCasa;
    private javax.swing.JFormattedTextField arancel;
    private javax.swing.JFormattedTextField arancelbursatil;
    private javax.swing.JButton bGenerar;
    private javax.swing.JFormattedTextField base;
    private javax.swing.JButton buscartitulo;
    private javax.swing.JTextField capital;
    private javax.swing.JFormattedTextField codmoneda;
    private javax.swing.JComboBox combotitulo;
    private javax.swing.JFormattedTextField comision;
    private javax.swing.JFormattedTextField comision_intermediacion;
    private javax.swing.JFormattedTextField cupones;
    private com.toedter.calendar.JDateChooser dCompra;
    private com.toedter.calendar.JDateChooser dEmision;
    private com.toedter.calendar.JDateChooser dFechaOperacion;
    private com.toedter.calendar.JDateChooser dUltimoCupon;
    private com.toedter.calendar.JDateChooser dVence;
    private org.edisoncor.gui.label.LabelMetric etiquetavacaciones;
    private javax.swing.JFormattedTextField inversion;
    private javax.swing.JTextField isin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField meses_restantes;
    private javax.swing.JTextField moneda;
    private javax.swing.JFormattedTextField montoiva;
    private javax.swing.JTextField pagos;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JFormattedTextField porcentajetir;
    private javax.swing.JFormattedTextField precio;
    private javax.swing.JFormattedTextField precioclean_flujo;
    private javax.swing.JTextField serie;
    private javax.swing.JTable tablacupones;
    private javax.swing.JTable tablatitulo;
    private javax.swing.JFormattedTextField tasa;
    private javax.swing.JFormattedTextField titulo;
    private javax.swing.JFormattedTextField total_a_recibir;
    private javax.swing.JFormattedTextField totalgastos;
    private javax.swing.JFormattedTextField totalintereses;
    private javax.swing.JTextField txtbuscartitulo;
    private javax.swing.JFormattedTextField valornominal;
    private javax.swing.JFormattedTextField valornominal_flujo;
    // End of variables declaration//GEN-END:variables

    private class CargarTitulos extends Thread {

        public void run() {
            //Antes de Cargar el Jtable Ajustamos el ancho de las columnas con el Ancho que se nos antoje
            int cantidadRegistro = modelotitulo.getRowCount();
            for (int i = 1; i <= cantidadRegistro; i++) {
                modelotitulo.removeRow(0);
            }

            tituloDAO titDAO = new tituloDAO();
            try {
                for (titulo tit : titDAO.todoOperaciones(1)) {
                    String Datos[] = {String.valueOf(tit.getCodigo()), tit.getNomalias(), tit.getEmpresa().getNombre()};
                    modelotitulo.addRow(Datos);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
            }

            tablatitulo.setRowSorter(new TableRowSorter(modelotitulo));
            int cantFilas = tablatitulo.getRowCount();
        }
    }

}
